package com.shipflow.billing;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.shipflow.billing.api.model.*;
import com.shipflow.billing.application.*;
import com.shipflow.billing.domain.*;
import com.shipflow.billing.mapper.BillingMapper;
import org.junit.jupiter.api.*;
import org.springframework.mock.web.MockMultipartFile;
import java.math.BigDecimal;
import java.time.*;
import java.util.*;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

class BillingApplicationServiceTest {
 private static final LocalDateTime NOW=LocalDateTime.of(2026,8,11,12,0); private BillingMapper mapper; private BillingApplicationService service;
 @BeforeEach void setUp(){mapper=mock(BillingMapper.class);when(mapper.finishBatch(anyLong(),anyLong(),anyInt(),anyInt(),anyInt(),anyString(),anyLong())).thenReturn(1);when(mapper.completeIdempotency(anyLong(),anyString(),anyString(),anyString(),anyLong(),anyInt())).thenReturn(1);when(mapper.findBatch(7L,41L)).thenReturn(batch(41L,"SUCCESS",1L));service=new BillingApplicationService(mapper,new ObjectMapper(),Clock.fixed(NOW.toInstant(ZoneOffset.UTC),ZoneOffset.UTC));}
 @Test void importsMatchedAndDifferentRowsThenCreatesAutomaticReconciliation(){when(mapper.providerExists(3L)).thenReturn(true);when(mapper.findIdempotency(eq(7L),eq("importBillingCsv"),eq("bill-key"))).thenReturn(null);when(mapper.findBatchByHash(eq(7L),eq(3L),anyString())).thenReturn(null,batch(41L,"PROCESSING",0L),batch(41L,"SUCCESS",1L));when(mapper.findOrderByTracking(7L,3L,"TN1")).thenReturn(new OrderFeeMatch(9L,new BigDecimal("10.00"),"USD"));when(mapper.findDetailByBatchLine(7L,41L,2)).thenReturn(detail(51L,"MATCHED"));var result=service.importCsv(7L,2L,3L,file("D1,TN1,12.00,USD,FREIGHT"),"bill-key","req-1");assertThat(result.status()).isEqualTo("SUCCESS");verify(mapper).insertDetail(eq(7L),eq(41L),eq(3L),eq("D1"),eq(2),eq(9L),eq("TN1"),eq(new BigDecimal("12.00")),eq("USD"),eq("FREIGHT"),eq("MATCHED"),isNull());verify(mapper).insertReconciliation(7L,9L,51L,new BigDecimal("10.00"),new BigDecimal("12.00"),new BigDecimal("2.00"),"PENDING_CONFIRMATION");verify(mapper).finishBatch(7L,41L,1,1,0,"SUCCESS",0L);verify(mapper).completeIdempotency(7L,"importBillingCsv","bill-key","BILL_IMPORT_BATCH",41L,202);verify(mapper).insertAudit(eq(7L),eq(2L),eq("BILL_IMPORT"),eq("BILL_IMPORT_BATCH"),eq(41L),eq("req-1"),isNull(),contains("fileHash"),eq(NOW));}
 @Test void exactAmountIsAutoClosed(){when(mapper.providerExists(3L)).thenReturn(true);when(mapper.findIdempotency(anyLong(),anyString(),anyString())).thenReturn(null);when(mapper.findBatchByHash(eq(7L),eq(3L),anyString())).thenReturn(null,batch(41L,"PROCESSING",0L),batch(41L,"SUCCESS",1L));when(mapper.findOrderByTracking(7L,3L,"TN1")).thenReturn(new OrderFeeMatch(9L,new BigDecimal("10.00"),"USD"));when(mapper.findDetailByBatchLine(7L,41L,2)).thenReturn(detail(51L,"MATCHED"));service.importCsv(7L,2L,3L,file("D1,TN1,10.00,USD,FREIGHT"),"bill-key",null);verify(mapper).insertReconciliation(7L,9L,51L,new BigDecimal("10.00"),new BigDecimal("10.00"),new BigDecimal("0.00"),"AUTO_CLOSED");}
 @Test void repeatedTenantProviderHashReturnsOriginalWithoutWrites(){when(mapper.providerExists(3L)).thenReturn(true);when(mapper.findIdempotency(anyLong(),anyString(),anyString())).thenReturn(null);when(mapper.findBatchByHash(eq(7L),eq(3L),anyString())).thenReturn(batch(41L,"SUCCESS",1L));var result=service.importCsv(7L,2L,3L,file("D1,TN1,10.00,USD,FREIGHT"),"bill-key",null);assertThat(result.id()).isEqualTo(41L);verify(mapper).completeIdempotency(7L,"importBillingCsv","bill-key","BILL_IMPORT_BATCH",41L,202);verify(mapper,never()).insertBatch(any(),any(),any(),any(),anyString(),anyLong(),any());verify(mapper,never()).insertDetail(any(),any(),any(),any(),anyInt(),any(),any(),any(),any(),any(),any(),any());}
 @Test void duplicateLineIsCountedAsFailureWithoutSecondDetail(){when(mapper.providerExists(3L)).thenReturn(true);when(mapper.findIdempotency(anyLong(),anyString(),anyString())).thenReturn(null);when(mapper.findBatchByHash(eq(7L),eq(3L),anyString())).thenReturn(null,batch(41L,"PROCESSING",0L),batch(41L,"PARTIAL_SUCCESS",1L));when(mapper.findOrderByTracking(7L,3L,"TN1")).thenReturn(new OrderFeeMatch(9L,new BigDecimal("10.00"),"USD"));when(mapper.findDetailByBatchLine(7L,41L,2)).thenReturn(detail(51L,"MATCHED"));service.importCsv(7L,2L,3L,file("D1,TN1,10.00,USD,FREIGHT\nD1,TN1,10.00,USD,FREIGHT"),"bill-key",null);verify(mapper,times(1)).insertDetail(any(),any(),any(),any(),anyInt(),any(),any(),any(),any(),any(),any(),any());verify(mapper).finishBatch(7L,41L,2,1,1,"PARTIAL_SUCCESS",0L);}
 @Test void unmatchedTrackingCreatesErrorDetailAndNoReconciliation(){when(mapper.providerExists(3L)).thenReturn(true);when(mapper.findIdempotency(anyLong(),anyString(),anyString())).thenReturn(null);when(mapper.findBatchByHash(eq(7L),eq(3L),anyString())).thenReturn(null,batch(41L,"PROCESSING",0L),batch(41L,"FAILED",1L));when(mapper.findOrderByTracking(7L,3L,"MISS")).thenReturn(null);service.importCsv(7L,2L,3L,file("D1,MISS,10.00,USD,FREIGHT"),"bill-key",null);verify(mapper).insertDetail(eq(7L),eq(41L),eq(3L),eq("D1"),eq(2),isNull(),eq("MISS"),eq(new BigDecimal("10.00")),eq("USD"),eq("FREIGHT"),eq("ERROR"),contains("not found"));verify(mapper,never()).insertReconciliation(any(),any(),any(),any(),any(),any(),any());}
 @Test void sameIdempotencyKeyWithDifferentFileIsRejected(){when(mapper.providerExists(3L)).thenReturn(true);when(mapper.findIdempotency(7L,"importBillingCsv","bill-key")).thenReturn(new BillingMapper.IdempotencyRecord("different-hash",null,"PROCESSING"));assertCode(()->service.importCsv(7L,2L,3L,file("D1,TN1,10.00,USD,FREIGHT"),"bill-key",null),"COMMON-1009",409);verify(mapper,never()).insertBatch(any(),any(),any(),any(),anyString(),anyLong(),any());}
 @Test void sameIdempotencyKeyInProcessingIsRejected(){when(mapper.providerExists(3L)).thenReturn(true);when(mapper.findIdempotency(7L,"importBillingCsv","bill-key")).thenReturn(new BillingMapper.IdempotencyRecord(""+"",null,"PROCESSING"));assertThatThrownBy(()->service.importCsv(7L,2L,3L,file("D1,TN1,10.00,USD,FREIGHT"),"bill-key",null)).isInstanceOf(BillingException.class);}
 @Test void crossTenantReconciliationIsUniformNotFound(){when(mapper.findReconciliation(7L,81L)).thenReturn(null);assertCode(()->service.getReconciliation(7L,2L,81L),"COMMON-1006",404);}
 @Test void confirmRequiresPendingStateAndUsesVersion(){when(mapper.findReconciliation(7L,81L)).thenReturn(recon(81L,"PENDING_CONFIRMATION",0L),recon(81L,"CONFIRMED",1L));when(mapper.hasReconciliationAccess(7L,2L,81L)).thenReturn(true);when(mapper.confirmReconciliation(7L,81L,2L,"ACCEPT","ok",NOW,0L)).thenReturn(1);assertThat(service.confirm(7L,2L,81L,new ReconciliationConfirmRequest("ACCEPT","ok",0L),"req").reconciliationStatus()).isEqualTo("CONFIRMED");verify(mapper).insertAudit(eq(7L),eq(2L),eq("RECONCILIATION_CONFIRM"),eq("RECONCILIATION_RECORD"),eq(81L),eq("req"),eq("ok"),contains("CONFIRMED"),eq(NOW));}
 @Test void confirmationOfAutoClosedOrRepeatedRecordIsRejected(){when(mapper.findReconciliation(7L,81L)).thenReturn(recon(81L,"AUTO_CLOSED",0L));when(mapper.hasReconciliationAccess(7L,2L,81L)).thenReturn(true);assertCode(()->service.confirm(7L,2L,81L,new ReconciliationConfirmRequest("ACCEPT","ok",0L),null),"RECON-1003",409);verify(mapper,never()).confirmReconciliation(any(),any(),any(),any(),any(),any(),any());}
 private MockMultipartFile file(String rows){return new MockMultipartFile("file","bill.csv","text/csv",("provider_bill_detail_no,tracking_no,billed_amount,currency,fee_type\n"+rows).getBytes(java.nio.charset.StandardCharsets.UTF_8));}
 private BillImportBatch batch(Long id,String status,Long version){return new BillImportBatch(id,7L,3L,"BILL1","bill.csv","a".repeat(64),20,1,1,0,status,NOW,version,NOW,NOW);}
 private BillDetail detail(Long id,String status){return new BillDetail(id,7L,41L,3L,"D1",2,9L,"TN1",new BigDecimal("10.00"),"USD","FREIGHT",status,null,NOW,NOW);}
 private ReconciliationRecord recon(Long id,String status,Long version){return new ReconciliationRecord(id,7L,9L,51L,new BigDecimal("10.00"),new BigDecimal("12.00"),new BigDecimal("2.00"),status,null,null,null,null,version,NOW,NOW);}
 private void assertCode(org.assertj.core.api.ThrowableAssert.ThrowingCallable call,String code,int status){assertThatThrownBy(call).isInstanceOf(BillingException.class).satisfies(e->{assertThat(((BillingException)e).code()).isEqualTo(code);assertThat(((BillingException)e).status()).isEqualTo(status);});}
}
