[pytest]
testpaths=tests
python_files=test_*.py
python_classes=Test*
python_functions=test_*
addopts=-v
markers=
    smoke:核心冒烟测试
    auth:认证模块测试
    users:用户模块测试
    negative:异常场景测试
    database_driven: 数据库驱动接口自动化用例