package com.shipflow.audit.api;
import com.shipflow.audit.api.model.*; import com.shipflow.audit.application.*; import com.shipflow.common.api.ApiResponse; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.security.oauth2.jwt.Jwt; import org.springframework.web.bind.annotation.*; import java.time.OffsetDateTime;
@RestController @RequestMapping("/api/v1") public class AuditQueryController {
 private final AuditQueryApplicationService service; public AuditQueryController(AuditQueryApplicationService service){this.service=service;}
 @GetMapping("/audit-logs") public ApiResponse<AuditLogPageResponse> list(@RequestParam(required=false) String resourceType,@RequestParam(required=false) Long resourceId,@RequestParam(required=false) String action,@RequestParam(required=false) Long operatorId,@RequestParam(required=false) OffsetDateTime from,@RequestParam(required=false) OffsetDateTime to,@RequestParam(defaultValue="1") int page,@RequestParam(defaultValue="20") int pageSize,@AuthenticationPrincipal Jwt jwt){return ApiResponse.success(service.list(tenant(jwt),resourceType,resourceId,action,operatorId,from,to,page,pageSize));}
 @GetMapping("/audit-logs/{auditId}") public ApiResponse<AuditLogResponse> get(@PathVariable Long auditId,@AuthenticationPrincipal Jwt jwt){return ApiResponse.success(service.get(tenant(jwt),auditId));}
 @GetMapping("/platform/audit-logs") public ApiResponse<AuditLogPageResponse> platformList(@RequestParam Long tenantId,@RequestParam(required=false) String resourceType,@RequestParam(required=false) Long resourceId,@RequestParam(required=false) String action,@RequestParam(required=false) Long operatorId,@RequestParam(required=false) OffsetDateTime from,@RequestParam(required=false) OffsetDateTime to,@RequestParam(defaultValue="1") int page,@RequestParam(defaultValue="20") int pageSize){return ApiResponse.success(service.listPlatform(tenantId,resourceType,resourceId,action,operatorId,from,to,page,pageSize));}
 @GetMapping("/platform/audit-logs/{auditId}") public ApiResponse<AuditLogResponse> platformGet(@PathVariable Long auditId,@RequestParam Long tenantId){return ApiResponse.success(service.getPlatform(tenantId,auditId));}
 private Long tenant(Jwt jwt){try{return Long.valueOf(jwt.getClaimAsString("tenant_id"));}catch(Exception e){throw new AuditQueryException("COMMON-1004",403);}}
}
