-- ShipFlow 认证模块 API 自动化测试用例
-- 可重复执行；所有敏感值均使用占位符，不保存真实密码、Token或密钥。
SET NAMES utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE shipflow_qa;

INSERT INTO api_test_case (
    case_no, module, title, test_type, priority, precondition,
    http_method, request_path, headers_template, cookie_template, request_body_template,
    expected_status, expected_error_code, assertions, data_dependency, enabled
) VALUES
-- GET /api/v1/auth/csrf：5条
('AUTH-CSRF-001', 'AUTH_CSRF', '匿名获取CSRF Token成功', 'NORMAL', 'P0', '服务已启动',
 'GET', '/api/v1/auth/csrf', JSON_OBJECT('Accept', 'application/json'), JSON_OBJECT(), NULL,
 204, NULL, JSON_ARRAY('响应头存在X-Trace-Id', 'Set-Cookie包含XSRF-TOKEN', '响应体为空'), '无', 1),
('AUTH-CSRF-002', 'AUTH_CSRF', '重复获取CSRF Token仍成功', 'BOUNDARY', 'P1', '客户端已有${XSRF_TOKEN}',
 'GET', '/api/v1/auth/csrf', JSON_OBJECT('Accept', 'application/json'), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN}'), NULL,
 204, NULL, JSON_ARRAY('响应仍为204', '返回可用于后续请求的XSRF-TOKEN', '不创建Refresh Cookie'), '${XSRF_TOKEN}', 1),
('AUTH-CSRF-003', 'AUTH_CSRF', 'CSRF响应禁止缓存', 'SECURITY', 'P0', '服务已启动',
 'GET', '/api/v1/auth/csrf', JSON_OBJECT(), JSON_OBJECT(), NULL,
 204, NULL, JSON_ARRAY('Cache-Control包含no-store', '响应头存在X-Trace-Id'), '无', 1),
('AUTH-CSRF-004', 'AUTH_CSRF', '生产环境XSRF Cookie安全属性正确', 'SECURITY', 'P0', '生产等价配置启用Cookie Secure',
 'GET', '/api/v1/auth/csrf', JSON_OBJECT(), JSON_OBJECT(), NULL,
 204, NULL, JSON_ARRAY('XSRF-TOKEN不含HttpOnly', '包含Secure', 'SameSite=Strict', 'Path=/api/v1/auth', '不设置Domain', 'Max-Age为正数'), '运行环境${COOKIE_SECURE}=true', 1),
('AUTH-CSRF-005', 'AUTH_CSRF', 'CSRF响应不泄露认证凭证', 'SECURITY', 'P0', '服务已启动',
 'GET', '/api/v1/auth/csrf', JSON_OBJECT(), JSON_OBJECT(), NULL,
 204, NULL, JSON_ARRAY('响应体不含password', '响应体不含passwordHash', '响应体不含accessToken', 'Set-Cookie不含SHIPFLOW_REFRESH_TOKEN'), '无', 1),

-- POST /api/v1/auth/login：18条
('AUTH-LOGIN-001', 'AUTH_LOGIN', '租户管理员登录成功', 'NORMAL', 'P0', 'ACTIVE租户、用户、角色和已知测试密码已准备',
 'POST', '/api/v1/auth/login', JSON_OBJECT('Content-Type', 'application/json', 'X-XSRF-TOKEN', '${XSRF_TOKEN}'), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN}'),
 '{"tenantCode":"${TENANT_CODE_A}","username":"${TENANT_ADMIN_USERNAME}","password":"${VALID_PASSWORD}"}',
 200, NULL, JSON_ARRAY('success=true', 'data.accessToken非空', 'data.tokenType=Bearer', 'data.expiresIn=900', '响应头存在X-Trace-Id'), '${TENANT_CODE_A}, ${TENANT_ADMIN_USERNAME}, ${VALID_PASSWORD}, ${XSRF_TOKEN}', 1),
('AUTH-LOGIN-002', 'AUTH_LOGIN', '平台管理员登录成功且不传tenantCode', 'NORMAL', 'P0', 'ACTIVE平台管理员和已知测试密码已准备',
 'POST', '/api/v1/auth/login', JSON_OBJECT('Content-Type', 'application/json', 'X-XSRF-TOKEN', '${XSRF_TOKEN}'), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN}'),
 '{"username":"${PLATFORM_ADMIN_USERNAME}","password":"${VALID_PASSWORD}"}',
 200, NULL, JSON_ARRAY('success=true', 'JWT scope=PLATFORM', 'JWT不包含tenant_id'), '${PLATFORM_ADMIN_USERNAME}, ${VALID_PASSWORD}, ${XSRF_TOKEN}', 1),
('AUTH-LOGIN-003', 'AUTH_LOGIN', '缺少username参数', 'EXCEPTION', 'P1', '已获取CSRF Token',
 'POST', '/api/v1/auth/login', JSON_OBJECT('Content-Type', 'application/json', 'X-XSRF-TOKEN', '${XSRF_TOKEN}'), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN}'),
 '{"tenantCode":"${TENANT_CODE_A}","password":"${VALID_PASSWORD}"}',
 400, 'COMMON-1001', JSON_ARRAY('success=false', 'error.code=COMMON-1001', '响应不泄露密码'), '${XSRF_TOKEN}', 1),
('AUTH-LOGIN-004', 'AUTH_LOGIN', '缺少password参数', 'EXCEPTION', 'P1', '已获取CSRF Token',
 'POST', '/api/v1/auth/login', JSON_OBJECT('Content-Type', 'application/json', 'X-XSRF-TOKEN', '${XSRF_TOKEN}'), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN}'),
 '{"tenantCode":"${TENANT_CODE_A}","username":"${TENANT_ADMIN_USERNAME}"}',
 400, 'COMMON-1001', JSON_ARRAY('success=false', 'error.code=COMMON-1001'), '${XSRF_TOKEN}', 1),
('AUTH-LOGIN-005', 'AUTH_LOGIN', 'username和password为空字符串', 'BOUNDARY', 'P1', '已获取CSRF Token',
 'POST', '/api/v1/auth/login', JSON_OBJECT('Content-Type', 'application/json', 'X-XSRF-TOKEN', '${XSRF_TOKEN}'), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN}'),
 '{"tenantCode":"${TENANT_CODE_A}","username":"","password":""}',
 400, 'COMMON-1001', JSON_ARRAY('success=false', 'error.code=COMMON-1001'), '${XSRF_TOKEN}', 1),
('AUTH-LOGIN-006', 'AUTH_LOGIN', 'username和password为null', 'BOUNDARY', 'P1', '已获取CSRF Token',
 'POST', '/api/v1/auth/login', JSON_OBJECT('Content-Type', 'application/json', 'X-XSRF-TOKEN', '${XSRF_TOKEN}'), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN}'),
 '{"tenantCode":"${TENANT_CODE_A}","username":null,"password":null}',
 400, 'COMMON-1001', JSON_ARRAY('success=false', 'error.code=COMMON-1001'), '${XSRF_TOKEN}', 1),
('AUTH-LOGIN-007', 'AUTH_LOGIN', '登录请求体不是合法JSON', 'EXCEPTION', 'P1', '已获取CSRF Token',
 'POST', '/api/v1/auth/login', JSON_OBJECT('Content-Type', 'application/json', 'X-XSRF-TOKEN', '${XSRF_TOKEN}'), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN}'),
 '{"tenantCode":',
 400, 'COMMON-1008', JSON_ARRAY('success=false', 'error.code=COMMON-1008', '不返回Spring默认错误页'), '${XSRF_TOKEN}', 1),
('AUTH-LOGIN-008', 'AUTH_LOGIN', '错误tenantCode统一认证失败', 'SECURITY', 'P0', '用户名和密码本身有效',
 'POST', '/api/v1/auth/login', JSON_OBJECT('Content-Type', 'application/json', 'X-XSRF-TOKEN', '${XSRF_TOKEN}'), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN}'),
 '{"tenantCode":"${WRONG_TENANT_CODE}","username":"${TENANT_ADMIN_USERNAME}","password":"${VALID_PASSWORD}"}',
 401, 'AUTH-1001', JSON_ARRAY('error.code=AUTH-1001', '错误消息不泄露租户是否存在'), '${WRONG_TENANT_CODE}, ${XSRF_TOKEN}', 1),
('AUTH-LOGIN-009', 'AUTH_LOGIN', '错误username统一认证失败', 'SECURITY', 'P0', '租户和密码有效',
 'POST', '/api/v1/auth/login', JSON_OBJECT('Content-Type', 'application/json', 'X-XSRF-TOKEN', '${XSRF_TOKEN}'), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN}'),
 '{"tenantCode":"${TENANT_CODE_A}","username":"${WRONG_USERNAME}","password":"${VALID_PASSWORD}"}',
 401, 'AUTH-1001', JSON_ARRAY('error.code=AUTH-1001', '错误消息不泄露用户是否存在'), '${WRONG_USERNAME}, ${XSRF_TOKEN}', 1),
('AUTH-LOGIN-010', 'AUTH_LOGIN', '错误密码统一认证失败', 'SECURITY', 'P0', '租户和用户有效',
 'POST', '/api/v1/auth/login', JSON_OBJECT('Content-Type', 'application/json', 'X-XSRF-TOKEN', '${XSRF_TOKEN}'), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN}'),
 '{"tenantCode":"${TENANT_CODE_A}","username":"${TENANT_ADMIN_USERNAME}","password":"${INVALID_PASSWORD}"}',
 401, 'AUTH-1001', JSON_ARRAY('error.code=AUTH-1001', '响应不包含password或passwordHash'), '${INVALID_PASSWORD}, ${XSRF_TOKEN}', 1),
('AUTH-LOGIN-011', 'AUTH_LOGIN', 'DISABLED用户禁止登录', 'STATE_FLOW', 'P0', '用户状态为DISABLED，租户和角色ACTIVE',
 'POST', '/api/v1/auth/login', JSON_OBJECT('Content-Type', 'application/json', 'X-XSRF-TOKEN', '${XSRF_TOKEN}'), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN}'),
 '{"tenantCode":"${TENANT_CODE_A}","username":"${DISABLED_USER}","password":"${VALID_PASSWORD}"}',
 401, 'AUTH-1001', JSON_ARRAY('error.code=AUTH-1001', '不泄露用户被禁用'), '${DISABLED_USER}, ${XSRF_TOKEN}', 1),
('AUTH-LOGIN-012', 'AUTH_LOGIN', 'DISABLED租户禁止登录', 'STATE_FLOW', 'P0', '租户状态为DISABLED，用户和角色ACTIVE',
 'POST', '/api/v1/auth/login', JSON_OBJECT('Content-Type', 'application/json', 'X-XSRF-TOKEN', '${XSRF_TOKEN}'), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN}'),
 '{"tenantCode":"${DISABLED_TENANT_CODE}","username":"${DISABLED_TENANT_USER}","password":"${VALID_PASSWORD}"}',
 401, 'AUTH-1001', JSON_ARRAY('error.code=AUTH-1001', '不泄露租户被禁用'), '${DISABLED_TENANT_CODE}, ${XSRF_TOKEN}', 1),
('AUTH-LOGIN-013', 'AUTH_LOGIN', '仅有DISABLED角色的用户禁止登录', 'STATE_FLOW', 'P0', '用户和租户ACTIVE，用户角色全部DISABLED',
 'POST', '/api/v1/auth/login', JSON_OBJECT('Content-Type', 'application/json', 'X-XSRF-TOKEN', '${XSRF_TOKEN}'), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN}'),
 '{"tenantCode":"${TENANT_CODE_A}","username":"${DISABLED_ROLE_USER}","password":"${VALID_PASSWORD}"}',
 401, 'AUTH-1001', JSON_ARRAY('error.code=AUTH-1001', '不泄露角色状态'), '${DISABLED_ROLE_USER}, ${XSRF_TOKEN}', 1),
('AUTH-LOGIN-014', 'AUTH_LOGIN', '同名用户不能跨租户回退登录', 'SECURITY', 'P0', '租户A和租户B存在同名用户且密码不同',
 'POST', '/api/v1/auth/login', JSON_OBJECT('Content-Type', 'application/json', 'X-XSRF-TOKEN', '${XSRF_TOKEN}'), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN}'),
 '{"tenantCode":"${TENANT_CODE_B}","username":"${CROSS_TENANT_USERNAME}","password":"${TENANT_A_PASSWORD}"}',
 401, 'AUTH-1001', JSON_ARRAY('error.code=AUTH-1001', '不得回退查询租户A或平台用户'), '${TENANT_CODE_B}, ${CROSS_TENANT_USERNAME}, ${XSRF_TOKEN}', 1),
('AUTH-LOGIN-015', 'AUTH_LOGIN', '缺少XSRF Cookie拒绝登录', 'SECURITY', 'P0', '请求头具有${XSRF_TOKEN}',
 'POST', '/api/v1/auth/login', JSON_OBJECT('Content-Type', 'application/json', 'X-XSRF-TOKEN', '${XSRF_TOKEN}'), JSON_OBJECT(),
 '{"tenantCode":"${TENANT_CODE_A}","username":"${TENANT_ADMIN_USERNAME}","password":"${VALID_PASSWORD}"}',
 403, 'AUTH-1005', JSON_ARRAY('error.code=AUTH-1005', '不执行密码认证'), '${XSRF_TOKEN}', 1),
('AUTH-LOGIN-016', 'AUTH_LOGIN', '缺少X-XSRF-TOKEN请求头拒绝登录', 'SECURITY', 'P0', 'Cookie具有${XSRF_TOKEN}',
 'POST', '/api/v1/auth/login', JSON_OBJECT('Content-Type', 'application/json'), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN}'),
 '{"tenantCode":"${TENANT_CODE_A}","username":"${TENANT_ADMIN_USERNAME}","password":"${VALID_PASSWORD}"}',
 403, 'AUTH-1005', JSON_ARRAY('error.code=AUTH-1005'), '${XSRF_TOKEN}', 1),
('AUTH-LOGIN-017', 'AUTH_LOGIN', 'XSRF Cookie与Header不一致拒绝登录', 'SECURITY', 'P0', '准备两个不同CSRF值',
 'POST', '/api/v1/auth/login', JSON_OBJECT('Content-Type', 'application/json', 'X-XSRF-TOKEN', '${XSRF_TOKEN_B}'), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN_A}'),
 '{"tenantCode":"${TENANT_CODE_A}","username":"${TENANT_ADMIN_USERNAME}","password":"${VALID_PASSWORD}"}',
 403, 'AUTH-1005', JSON_ARRAY('error.code=AUTH-1005'), '${XSRF_TOKEN_A}, ${XSRF_TOKEN_B}', 1),
('AUTH-LOGIN-018', 'AUTH_LOGIN', 'Mock物流账号禁止用户名密码登录', 'SECURITY', 'P0', 'Mock物流账号ACTIVE且具有tracking:callback权限',
 'POST', '/api/v1/auth/login', JSON_OBJECT('Content-Type', 'application/json', 'X-XSRF-TOKEN', '${XSRF_TOKEN}'), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN}'),
 '{"username":"${MOCK_LOGISTICS_USERNAME}","password":"${VALID_PASSWORD}"}',
 401, 'AUTH-1001', JSON_ARRAY('error.code=AUTH-1001', '不泄露其为系统账号'), '${MOCK_LOGISTICS_USERNAME}, ${XSRF_TOKEN}', 1),

-- GET /api/v1/users/me：9条
('AUTH-ME-001', 'AUTH_CURRENT_USER', '租户用户查询当前身份成功', 'NORMAL', 'P0', '持有有效租户Access Token',
 'GET', '/api/v1/users/me', JSON_OBJECT('Authorization', 'Bearer ${ACCESS_TOKEN}'), JSON_OBJECT(), NULL,
 200, NULL, JSON_ARRAY('success=true', '用户ID为字符串', 'tenantId等于Token租户', '返回当前有效权限', '响应头存在X-Trace-Id'), '${ACCESS_TOKEN}', 1),
('AUTH-ME-002', 'AUTH_CURRENT_USER', '平台用户查询当前身份成功', 'NORMAL', 'P1', '持有有效平台Access Token',
 'GET', '/api/v1/users/me', JSON_OBJECT('Authorization', 'Bearer ${PLATFORM_ACCESS_TOKEN}'), JSON_OBJECT(), NULL,
 200, NULL, JSON_ARRAY('scope=PLATFORM', 'tenantId不存在或为空'), '${PLATFORM_ACCESS_TOKEN}', 1),
('AUTH-ME-003', 'AUTH_CURRENT_USER', '缺少Access Token返回401', 'SECURITY', 'P0', '无',
 'GET', '/api/v1/users/me', JSON_OBJECT(), JSON_OBJECT(), NULL,
 401, 'COMMON-1002', JSON_ARRAY('error.code=COMMON-1002', 'WWW-Authenticate包含Bearer'), '无', 1),
('AUTH-ME-004', 'AUTH_CURRENT_USER', '篡改Access Token签名被拒绝', 'SECURITY', 'P0', '对有效Token payload做单字符篡改',
 'GET', '/api/v1/users/me', JSON_OBJECT('Authorization', 'Bearer ${TAMPERED_ACCESS_TOKEN}'), JSON_OBJECT(), NULL,
 401, 'COMMON-1002', JSON_ARRAY('error.code=COMMON-1002', 'WWW-Authenticate包含Bearer'), '${TAMPERED_ACCESS_TOKEN}', 1),
('AUTH-ME-005', 'AUTH_CURRENT_USER', '过期Access Token被拒绝', 'SECURITY', 'P0', '使用测试密钥签发已过期Token',
 'GET', '/api/v1/users/me', JSON_OBJECT('Authorization', 'Bearer ${EXPIRED_ACCESS_TOKEN}'), JSON_OBJECT(), NULL,
 401, 'COMMON-1003', JSON_ARRAY('error.code=COMMON-1003', 'WWW-Authenticate包含Bearer'), '${EXPIRED_ACCESS_TOKEN}', 1),
('AUTH-ME-006', 'AUTH_CURRENT_USER', 'issuer错误Access Token被拒绝', 'SECURITY', 'P0', '使用受信密钥但错误issuer签发Token',
 'GET', '/api/v1/users/me', JSON_OBJECT('Authorization', 'Bearer ${WRONG_ISSUER_ACCESS_TOKEN}'), JSON_OBJECT(), NULL,
 401, 'COMMON-1002', JSON_ARRAY('error.code=COMMON-1002'), '${WRONG_ISSUER_ACCESS_TOKEN}', 1),
('AUTH-ME-007', 'AUTH_CURRENT_USER', 'audience错误Access Token被拒绝', 'SECURITY', 'P0', '使用受信密钥但错误audience签发Token',
 'GET', '/api/v1/users/me', JSON_OBJECT('Authorization', 'Bearer ${WRONG_AUDIENCE_ACCESS_TOKEN}'), JSON_OBJECT(), NULL,
 401, 'COMMON-1002', JSON_ARRAY('error.code=COMMON-1002'), '${WRONG_AUDIENCE_ACCESS_TOKEN}', 1),
('AUTH-ME-008', 'AUTH_CURRENT_USER', 'Token租户与用户实际租户不一致时拒绝访问', 'SECURITY', 'P0', '测试签发tenant_id指向其他租户的Token',
 'GET', '/api/v1/users/me', JSON_OBJECT('Authorization', 'Bearer ${CROSS_TENANT_ACCESS_TOKEN}'), JSON_OBJECT(), NULL,
 401, 'COMMON-1002', JSON_ARRAY('不返回其他租户用户信息', '不泄露目标用户是否存在'), '${CROSS_TENANT_ACCESS_TOKEN}', 1),
('AUTH-ME-009', 'AUTH_CURRENT_USER', '当前用户响应不泄露敏感字段', 'SECURITY', 'P0', '持有有效Access Token',
 'GET', '/api/v1/users/me', JSON_OBJECT('Authorization', 'Bearer ${ACCESS_TOKEN}'), JSON_OBJECT(), NULL,
 200, NULL, JSON_ARRAY('响应不含password', '响应不含passwordHash', '响应不含refreshToken', '响应不含tokenHash'), '${ACCESS_TOKEN}', 1),

-- POST /api/v1/auth/refresh：12条
('AUTH-REFRESH-001', 'AUTH_REFRESH', 'Refresh Token正常轮换', 'STATE_FLOW', 'P0', '登录获得ACTIVE Refresh Cookie与CSRF Token',
 'POST', '/api/v1/auth/refresh', JSON_OBJECT('X-XSRF-TOKEN', '${XSRF_TOKEN}'), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN}', 'SHIPFLOW_REFRESH_TOKEN', '${REFRESH_COOKIE}'), NULL,
 200, NULL, JSON_ARRAY('返回新Access Token', 'Set-Cookie返回新Refresh Token', '新旧Refresh Token不同', '旧Session状态为ROTATED', '新Session状态为ACTIVE', 'familyId不变', 'expiresAt不延长'), '${XSRF_TOKEN}, ${REFRESH_COOKIE}', 1),
('AUTH-REFRESH-002', 'AUTH_REFRESH', '轮换后的旧Refresh Token不可再次正常刷新', 'STATE_FLOW', 'P0', '先执行AUTH-REFRESH-001并保存旧Cookie',
 'POST', '/api/v1/auth/refresh', JSON_OBJECT('X-XSRF-TOKEN', '${XSRF_TOKEN}'), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN}', 'SHIPFLOW_REFRESH_TOKEN', '${OLD_REFRESH_COOKIE}'), NULL,
 401, 'AUTH-1002', JSON_ARRAY('error.code=AUTH-1002', '不返回新Access Token'), '${OLD_REFRESH_COOKIE}, ${XSRF_TOKEN}', 1),
('AUTH-REFRESH-003', 'AUTH_REFRESH', '缺少Refresh Cookie返回统一失败', 'EXCEPTION', 'P0', 'CSRF合法',
 'POST', '/api/v1/auth/refresh', JSON_OBJECT('X-XSRF-TOKEN', '${XSRF_TOKEN}'), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN}'), NULL,
 401, 'AUTH-1002', JSON_ARRAY('error.code=AUTH-1002', '不泄露Token不存在'), '${XSRF_TOKEN}', 1),
('AUTH-REFRESH-004', 'AUTH_REFRESH', '非法Refresh Token返回统一失败', 'SECURITY', 'P0', 'CSRF合法',
 'POST', '/api/v1/auth/refresh', JSON_OBJECT('X-XSRF-TOKEN', '${XSRF_TOKEN}'), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN}', 'SHIPFLOW_REFRESH_TOKEN', '${INVALID_REFRESH_COOKIE}'), NULL,
 401, 'AUTH-1002', JSON_ARRAY('error.code=AUTH-1002', '不泄露摘要或查找结果'), '${INVALID_REFRESH_COOKIE}, ${XSRF_TOKEN}', 1),
('AUTH-REFRESH-005', 'AUTH_REFRESH', '绝对有效期已过的Refresh Token被拒绝', 'STATE_FLOW', 'P0', 'Refresh Session expires_at早于当前UTC时间',
 'POST', '/api/v1/auth/refresh', JSON_OBJECT('X-XSRF-TOKEN', '${XSRF_TOKEN}'), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN}', 'SHIPFLOW_REFRESH_TOKEN', '${EXPIRED_REFRESH_COOKIE}'), NULL,
 401, 'AUTH-1003', JSON_ARRAY('error.code=AUTH-1003', '不产生子Session'), '${EXPIRED_REFRESH_COOKIE}, ${XSRF_TOKEN}', 1),
('AUTH-REFRESH-006', 'AUTH_REFRESH', '缺少XSRF Cookie拒绝刷新', 'SECURITY', 'P0', 'Refresh Cookie和Header存在',
 'POST', '/api/v1/auth/refresh', JSON_OBJECT('X-XSRF-TOKEN', '${XSRF_TOKEN}'), JSON_OBJECT('SHIPFLOW_REFRESH_TOKEN', '${REFRESH_COOKIE}'), NULL,
 403, 'AUTH-1005', JSON_ARRAY('error.code=AUTH-1005', 'Refresh Session状态不变化'), '${REFRESH_COOKIE}, ${XSRF_TOKEN}', 1),
('AUTH-REFRESH-007', 'AUTH_REFRESH', '缺少X-XSRF-TOKEN Header拒绝刷新', 'SECURITY', 'P0', 'Refresh和XSRF Cookie存在',
 'POST', '/api/v1/auth/refresh', JSON_OBJECT(), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN}', 'SHIPFLOW_REFRESH_TOKEN', '${REFRESH_COOKIE}'), NULL,
 403, 'AUTH-1005', JSON_ARRAY('error.code=AUTH-1005', 'Refresh Session状态不变化'), '${REFRESH_COOKIE}, ${XSRF_TOKEN}', 1),
('AUTH-REFRESH-008', 'AUTH_REFRESH', 'XSRF Cookie与Header不一致拒绝刷新', 'SECURITY', 'P0', '准备两个不同CSRF值',
 'POST', '/api/v1/auth/refresh', JSON_OBJECT('X-XSRF-TOKEN', '${XSRF_TOKEN_B}'), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN_A}', 'SHIPFLOW_REFRESH_TOKEN', '${REFRESH_COOKIE}'), NULL,
 403, 'AUTH-1005', JSON_ARRAY('error.code=AUTH-1005', 'Refresh Session状态不变化'), '${REFRESH_COOKIE}, ${XSRF_TOKEN_A}, ${XSRF_TOKEN_B}', 1),
('AUTH-REFRESH-009', 'AUTH_REFRESH', 'ROTATED Token重放撤销整个family', 'STATE_FLOW', 'P0', '同一family存在ROTATED父Session和ACTIVE子Session',
 'POST', '/api/v1/auth/refresh', JSON_OBJECT('X-XSRF-TOKEN', '${XSRF_TOKEN}'), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN}', 'SHIPFLOW_REFRESH_TOKEN', '${ROTATED_REFRESH_COOKIE}'), NULL,
 401, 'AUTH-1002', JSON_ARRAY('error.code=AUTH-1002', 'family内ACTIVE Session变为REVOKED', '数据库断言整个family无ACTIVE记录'), '${ROTATED_REFRESH_COOKIE}, ${XSRF_TOKEN}', 1),
('AUTH-REFRESH-010', 'AUTH_REFRESH', '用户禁用后Refresh失败且不沿用旧权限', 'STATE_FLOW', 'P0', '签发Refresh后将用户状态改为DISABLED',
 'POST', '/api/v1/auth/refresh', JSON_OBJECT('X-XSRF-TOKEN', '${XSRF_TOKEN}'), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN}', 'SHIPFLOW_REFRESH_TOKEN', '${REFRESH_COOKIE}'), NULL,
 401, 'AUTH-1002', JSON_ARRAY('error.code=AUTH-1002', '不返回Access Token', '不使用旧权限快照'), '${REFRESH_COOKIE}, ${DISABLED_USER}, ${XSRF_TOKEN}', 1),
('AUTH-REFRESH-011', 'AUTH_REFRESH', '租户或角色禁用后Refresh失败', 'STATE_FLOW', 'P0', '参数化执行：租户DISABLED或用户全部角色DISABLED',
 'POST', '/api/v1/auth/refresh', JSON_OBJECT('X-XSRF-TOKEN', '${XSRF_TOKEN}'), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN}', 'SHIPFLOW_REFRESH_TOKEN', '${REFRESH_COOKIE}'), NULL,
 401, 'AUTH-1002', JSON_ARRAY('error.code=AUTH-1002', '不返回Access Token', '刷新时重新加载当前状态和权限'), '${REFRESH_COOKIE}, ${DISABLE_TARGET}, ${XSRF_TOKEN}', 1),
('AUTH-REFRESH-012', 'AUTH_REFRESH', '刷新响应的Cookie和缓存安全属性正确', 'SECURITY', 'P0', '生产等价配置且Refresh成功',
 'POST', '/api/v1/auth/refresh', JSON_OBJECT('X-XSRF-TOKEN', '${XSRF_TOKEN}'), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN}', 'SHIPFLOW_REFRESH_TOKEN', '${REFRESH_COOKIE}'), NULL,
 200, NULL, JSON_ARRAY('Cache-Control包含no-store', 'Refresh Cookie包含HttpOnly', '包含Secure', 'SameSite=Strict', 'Path=/api/v1/auth', '响应JSON不含refreshToken或tokenHash'), '${REFRESH_COOKIE}, ${XSRF_TOKEN}, ${COOKIE_SECURE}=true', 1),

-- POST /api/v1/auth/logout：8条
('AUTH-LOGOUT-001', 'AUTH_LOGOUT', '使用Refresh Cookie退出成功', 'STATE_FLOW', 'P0', '存在ACTIVE Refresh family且CSRF合法',
 'POST', '/api/v1/auth/logout', JSON_OBJECT('X-XSRF-TOKEN', '${XSRF_TOKEN}'), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN}', 'SHIPFLOW_REFRESH_TOKEN', '${REFRESH_COOKIE}'), NULL,
 200, NULL, JSON_ARRAY('success=true', '当前family全部撤销', '清除Refresh Cookie', '清除XSRF Cookie', 'Cache-Control包含no-store'), '${REFRESH_COOKIE}, ${XSRF_TOKEN}', 1),
('AUTH-LOGOUT-002', 'AUTH_LOGOUT', '缺少Refresh Cookie仍幂等成功', 'BOUNDARY', 'P0', 'CSRF合法',
 'POST', '/api/v1/auth/logout', JSON_OBJECT('X-XSRF-TOKEN', '${XSRF_TOKEN}'), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN}'), NULL,
 200, NULL, JSON_ARRAY('success=true', '清除客户端Refresh和XSRF Cookie', '不泄露Cookie不存在'), '${XSRF_TOKEN}', 1),
('AUTH-LOGOUT-003', 'AUTH_LOGOUT', '非法、过期或已撤销Refresh Cookie均幂等成功', 'BOUNDARY', 'P1', '参数化使用三种无效Refresh Cookie',
 'POST', '/api/v1/auth/logout', JSON_OBJECT('X-XSRF-TOKEN', '${XSRF_TOKEN}'), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN}', 'SHIPFLOW_REFRESH_TOKEN', '${NON_ACTIVE_REFRESH_COOKIE}'), NULL,
 200, NULL, JSON_ARRAY('success=true', '不区分非法、过期、撤销原因', '清除Cookie'), '${NON_ACTIVE_REFRESH_COOKIE}, ${XSRF_TOKEN}', 1),
('AUTH-LOGOUT-004', 'AUTH_LOGOUT', '重复Logout保持幂等成功', 'STATE_FLOW', 'P0', '同一family已执行过Logout',
 'POST', '/api/v1/auth/logout', JSON_OBJECT('X-XSRF-TOKEN', '${XSRF_TOKEN}'), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN}', 'SHIPFLOW_REFRESH_TOKEN', '${REVOKED_REFRESH_COOKIE}'), NULL,
 200, NULL, JSON_ARRAY('第二次仍success=true', 'family状态保持REVOKED', '不新增Session'), '${REVOKED_REFRESH_COOKIE}, ${XSRF_TOKEN}', 1),
('AUTH-LOGOUT-005', 'AUTH_LOGOUT', '缺少XSRF Cookie拒绝Logout', 'SECURITY', 'P0', 'Refresh Cookie和Header存在',
 'POST', '/api/v1/auth/logout', JSON_OBJECT('X-XSRF-TOKEN', '${XSRF_TOKEN}'), JSON_OBJECT('SHIPFLOW_REFRESH_TOKEN', '${REFRESH_COOKIE}'), NULL,
 403, 'AUTH-1005', JSON_ARRAY('error.code=AUTH-1005', 'family仍为ACTIVE'), '${REFRESH_COOKIE}, ${XSRF_TOKEN}', 1),
('AUTH-LOGOUT-006', 'AUTH_LOGOUT', '缺少X-XSRF-TOKEN Header拒绝Logout', 'SECURITY', 'P0', 'Refresh和XSRF Cookie存在',
 'POST', '/api/v1/auth/logout', JSON_OBJECT(), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN}', 'SHIPFLOW_REFRESH_TOKEN', '${REFRESH_COOKIE}'), NULL,
 403, 'AUTH-1005', JSON_ARRAY('error.code=AUTH-1005', 'family仍为ACTIVE'), '${REFRESH_COOKIE}, ${XSRF_TOKEN}', 1),
('AUTH-LOGOUT-007', 'AUTH_LOGOUT', 'XSRF Cookie与Header不一致拒绝Logout', 'SECURITY', 'P0', '准备两个不同CSRF值',
 'POST', '/api/v1/auth/logout', JSON_OBJECT('X-XSRF-TOKEN', '${XSRF_TOKEN_B}'), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN_A}', 'SHIPFLOW_REFRESH_TOKEN', '${REFRESH_COOKIE}'), NULL,
 403, 'AUTH-1005', JSON_ARRAY('error.code=AUTH-1005', 'family仍为ACTIVE'), '${REFRESH_COOKIE}, ${XSRF_TOKEN_A}, ${XSRF_TOKEN_B}', 1),
('AUTH-LOGOUT-008', 'AUTH_LOGOUT', 'Logout后旧Refresh Token不可继续刷新', 'STATE_FLOW', 'P0', '先成功执行AUTH-LOGOUT-001',
 'POST', '/api/v1/auth/logout', JSON_OBJECT('X-XSRF-TOKEN', '${XSRF_TOKEN}'), JSON_OBJECT('XSRF-TOKEN', '${XSRF_TOKEN}', 'SHIPFLOW_REFRESH_TOKEN', '${REFRESH_COOKIE}'), NULL,
 200, NULL, JSON_ARRAY('Logout成功', '随后用旧Refresh Token调用refresh返回401 AUTH-1002', 'family无ACTIVE Session'), '${REFRESH_COOKIE}, ${XSRF_TOKEN}, ${NEW_XSRF_TOKEN}', 1)
ON DUPLICATE KEY UPDATE
    module = VALUES(module),
    title = VALUES(title),
    test_type = VALUES(test_type),
    priority = VALUES(priority),
    precondition = VALUES(precondition),
    http_method = VALUES(http_method),
    request_path = VALUES(request_path),
    headers_template = VALUES(headers_template),
    cookie_template = VALUES(cookie_template),
    request_body_template = VALUES(request_body_template),
    expected_status = VALUES(expected_status),
    expected_error_code = VALUES(expected_error_code),
    assertions = VALUES(assertions),
    data_dependency = VALUES(data_dependency),
    enabled = VALUES(enabled);

-- 预期：52条认证测试用例，case_no无重复。
SELECT COUNT(*) AS enabled_auth_case_count
FROM api_test_case
WHERE enabled = 1 AND case_no LIKE 'AUTH-%';

SELECT request_path, http_method, COUNT(*) AS case_count
FROM api_test_case
WHERE enabled = 1 AND case_no LIKE 'AUTH-%'
GROUP BY request_path, http_method
ORDER BY request_path, http_method;
