package com.shipflow.store.api;
import com.shipflow.common.api.ApiResponse; import com.shipflow.store.api.model.*; import com.shipflow.store.application.StoreApplicationService; import com.shipflow.store.domain.model.*; import jakarta.validation.Valid; import org.springframework.http.*; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.security.oauth2.jwt.Jwt; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1/stores") public class StoreController {private final StoreApplicationService service; public StoreController(StoreApplicationService s){service=s;} private Long tenant(Jwt j){return Long.valueOf(j.getClaimAsString("tenant_id"));} private Long user(Jwt j){return Long.valueOf(j.getSubject());}
 @PostMapping public ResponseEntity<ApiResponse<Store>> create(@Valid @RequestBody CreateStoreRequest r,@RequestHeader(value="Idempotency-Key",required=false)String k,@RequestHeader(value="X-Request-Id",required=false)String q,@AuthenticationPrincipal Jwt j){return ResponseEntity.status(HttpStatus.CREATED).body(ApiResponse.success(service.create(tenant(j),r,k,user(j),q)));}
 @GetMapping public ApiResponse<StorePage> page(@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int pageSize,@RequestParam(required=false)String storeCode,@RequestParam(required=false)String storeName,@RequestParam(required=false)String platformCode,@RequestParam(required=false)String status,@RequestParam(defaultValue="updatedAt")String sortBy,@RequestParam(defaultValue="DESC")String sortDirection,@AuthenticationPrincipal Jwt j){return ApiResponse.success(service.page(tenant(j),user(j),storeCode,storeName,platformCode,status,sortBy,sortDirection,page,pageSize));}
 @GetMapping("/{id}") public ApiResponse<StoreDetailResponse> get(@PathVariable Long id,@AuthenticationPrincipal Jwt j){return ApiResponse.success(service.getDetail(tenant(j),user(j),id));}
 @GetMapping("/{id}/default-address") public ApiResponse<StoreAddressResponse> defaultAddress(@PathVariable Long id,@AuthenticationPrincipal Jwt j){return ApiResponse.success(service.defaultAddress(tenant(j),user(j),id));}
 @PutMapping("/{id}/default-address") public ApiResponse<StoreAddressResponse> updateDefaultAddress(@PathVariable Long id,@Valid @RequestBody UpdateStoreAddressRequest r,@RequestHeader("Idempotency-Key")String key,@RequestHeader(value="X-Request-Id",required=false)String q,@AuthenticationPrincipal Jwt j){return ApiResponse.success(service.updateDefaultAddress(tenant(j),user(j),id,r,key,q));}
 @GetMapping("/{id}/logistics-channels") public ApiResponse<java.util.List<StoreChannelResponse>> channels(@PathVariable Long id,@AuthenticationPrincipal Jwt j){return ApiResponse.success(service.channels(tenant(j),user(j),id));}
 @PutMapping("/{id}/default-logistics-channel") public ApiResponse<java.util.List<StoreChannelResponse>> setDefaultChannel(@PathVariable Long id,@Valid @RequestBody SetDefaultStoreChannelRequest r,@RequestHeader("Idempotency-Key")String key,@RequestHeader(value="X-Request-Id",required=false)String q,@AuthenticationPrincipal Jwt j){return ApiResponse.success(service.setDefaultChannel(tenant(j),user(j),id,r,key,q));}
 @PutMapping("/{id}") public ApiResponse<Store> update(@PathVariable Long id,@Valid @RequestBody UpdateStoreRequest r,@RequestHeader(value="Idempotency-Key")String key,@RequestHeader(value="X-Request-Id",required=false)String q,@AuthenticationPrincipal Jwt j){return ApiResponse.success(service.update(tenant(j),user(j),id,r,key,q));}
 @PostMapping("/{id}/status") public ApiResponse<Store> status(@PathVariable Long id,@Valid @RequestBody StoreStatusChangeRequest r,@RequestHeader(value="Idempotency-Key")String key,@RequestHeader(value="X-Request-Id",required=false)String q,@AuthenticationPrincipal Jwt j){return ApiResponse.success(service.status(tenant(j),user(j),id,r,key,q));}}
