package com.shipflow.audit;
import com.shipflow.audit.api.AuditQueryController; import com.shipflow.audit.api.model.*; import com.shipflow.audit.application.*; import java.time.*; import java.util.*; import org.junit.jupiter.api.Test; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest; import org.springframework.boot.test.context.TestConfiguration; import org.springframework.boot.test.mock.mockito.MockBean; import org.springframework.context.annotation.*; import org.springframework.security.core.authority.SimpleGrantedAuthority; import org.springframework.security.oauth2.jwt.JwtDecoder; import org.springframework.test.web.servlet.MockMvc; import static org.mockito.Mockito.*; import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.jwt; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@WebMvcTest(AuditQueryController.class) @Import({com.shipflow.security.SecurityConfig.class,com.shipflow.common.exception.GlobalExceptionHandler.class,AuditQueryControllerWebMvcTest.Config.class}) class AuditQueryControllerWebMvcTest {
 @Autowired MockMvc mvc; @MockBean AuditQueryApplicationService service; @TestConfiguration static class Config{@Bean JwtDecoder jwtDecoder(){return token->{throw new org.springframework.security.oauth2.jwt.BadJwtException("test");};}}
 @Test void tenantAdminListsOnlyJwtTenant() throws Exception {when(service.list(eq(7L),eq("ORDER"),eq(9L),eq("OUTBOUND"),eq(2L),any(),any(),eq(1),eq(20))).thenReturn(new AuditLogPageResponse(1,20,1,1,List.of(log())));mvc.perform(get("/api/v1/audit-logs").param("resourceType","ORDER").param("resourceId","9").param("action","OUTBOUND").param("operatorId","2").param("from","2026-08-11T10:00:00Z").param("to","2026-08-11T12:00:00Z").with(tenantAudit())).andExpect(status().isOk()).andExpect(jsonPath("$.data.items[0].id").value(11));verify(service).list(eq(7L),eq("ORDER"),eq(9L),eq("OUTBOUND"),eq(2L),any(),any(),eq(1),eq(20));}
 @Test void tenantAuditCannotUsePlatformEndpoint() throws Exception {mvc.perform(get("/api/v1/platform/audit-logs").param("tenantId","8").with(tenantAudit())).andExpect(status().isForbidden()).andExpect(jsonPath("$.error.code").value("COMMON-1004"));verifyNoInteractions(service);}
 @Test void platformCanQueryTargetTenant() throws Exception {when(service.listPlatform(eq(8L),isNull(),isNull(),isNull(),isNull(),isNull(),isNull(),eq(1),eq(20))).thenReturn(new AuditLogPageResponse(1,20,0,0,List.of()));mvc.perform(get("/api/v1/platform/audit-logs").param("tenantId","8").with(platformAudit())).andExpect(status().isOk());verify(service).listPlatform(eq(8L),isNull(),isNull(),isNull(),isNull(),isNull(),isNull(),eq(1),eq(20));}
 @Test void crossTenantDetailIsUnified404() throws Exception {when(service.get(7L,11L)).thenThrow(new AuditQueryException("COMMON-1006",404));mvc.perform(get("/api/v1/audit-logs/11").with(tenantAudit())).andExpect(status().isNotFound()).andExpect(jsonPath("$.error.code").value("COMMON-1006"));}
 @Test void missingAuditPermissionIsForbidden() throws Exception {mvc.perform(get("/api/v1/audit-logs").with(tenantOnly())).andExpect(status().isForbidden());verifyNoInteractions(service);}
 private org.springframework.test.web.servlet.request.RequestPostProcessor tenantAudit(){return jwt().jwt(j->j.subject("2").claim("tenant_id","7")).authorities(new SimpleGrantedAuthority("scope:TENANT"),new SimpleGrantedAuthority("audit:read"));} private org.springframework.test.web.servlet.request.RequestPostProcessor tenantOnly(){return jwt().jwt(j->j.subject("2").claim("tenant_id","7")).authorities(new SimpleGrantedAuthority("scope:TENANT"));} private org.springframework.test.web.servlet.request.RequestPostProcessor platformAudit(){return jwt().jwt(j->j.subject("1")).authorities(new SimpleGrantedAuthority("scope:PLATFORM"),new SimpleGrantedAuthority("audit:read"));} private AuditLogResponse log(){return new AuditLogResponse(11L,7L,2L,"OUTBOUND","ORDER",9L,"SUCCESS",Map.of("password","[REDACTED]"),OffsetDateTime.now(ZoneOffset.UTC),OffsetDateTime.now(ZoneOffset.UTC));}
}
