package com.shipflow.audit;
import com.fasterxml.jackson.databind.ObjectMapper; import com.shipflow.audit.application.*; import com.shipflow.audit.domain.AuditLog; import com.shipflow.audit.mapper.AuditQueryMapper; import org.junit.jupiter.api.*; import java.time.*; import java.util.*; import static org.assertj.core.api.Assertions.*; import static org.mockito.Mockito.*;
class AuditQueryApplicationServiceTest { private AuditQueryMapper mapper; private AuditQueryApplicationService service; private static final LocalDateTime NOW=LocalDateTime.of(2026,8,11,12,0);
 @BeforeEach void setUp(){mapper=mock(AuditQueryMapper.class);service=new AuditQueryApplicationService(mapper,new ObjectMapper());}
 @Test void pagesWithAllFiltersInsideCurrentTenant(){when(mapper.count(7L,"ORDER",9L,"OUTBOUND",2L,NOW.minusHours(1),NOW)).thenReturn(1L);when(mapper.findPage(7L,"ORDER",9L,"OUTBOUND",2L,NOW.minusHours(1),NOW,0,20)).thenReturn(List.of(log(11L,"{\"orderId\":9}")));var page=service.list(7L,"ORDER",9L,"OUTBOUND",2L,NOW.minusHours(1).atOffset(ZoneOffset.UTC),NOW.atOffset(ZoneOffset.UTC),1,20);assertThat(page.items()).hasSize(1);verify(mapper).findPage(7L,"ORDER",9L,"OUTBOUND",2L,NOW.minusHours(1),NOW,0,20);}
 @Test void missingOrCrossTenantDetailIsUniform404(){when(mapper.findById(7L,11L)).thenReturn(null);assertCode(()->service.get(7L,11L),"COMMON-1006",404);}
 @Test void platformMustTargetExistingTenant(){when(mapper.tenantExists(8L)).thenReturn(false);assertCode(()->service.listPlatform(8L,null,null,null,null,null,null,1,20),"COMMON-1006",404);}
 @Test void platformUsesRequestedTenant(){when(mapper.tenantExists(8L)).thenReturn(true);when(mapper.count(8L,null,null,null,null,null,null)).thenReturn(0L);when(mapper.findPage(8L,null,null,null,null,null,null,0,20)).thenReturn(List.of());service.listPlatform(8L,null,null,null,null,null,null,1,20);verify(mapper).count(8L,null,null,null,null,null,null);}
 @Test void stripsCredentialsTokensAndAddressDetails(){when(mapper.findById(7L,11L)).thenReturn(log(11L,"{\"password\":\"p\",\"jwt\":\"eyJabcdef123456789\",\"addressLine1\":\"secret road\",\"safe\":\"ok\",\"nested\":{\"refreshToken\":\"x\"}}"));var value=service.get(7L,11L);assertThat(value.detail()).containsEntry("safe","ok").containsEntry("password","[REDACTED]");assertThat(value.detail().get("jwt")).isEqualTo("[REDACTED]");assertThat(value.detail().get("addressLine1")).isEqualTo("[REDACTED]");@SuppressWarnings("unchecked") Map<String,Object> nested=(Map<String,Object>)value.detail().get("nested");assertThat(nested).containsEntry("refreshToken","[REDACTED]");}
 @Test void rejectsInvalidTimeRange(){assertCode(()->service.list(7L,null,null,null,null,NOW.atOffset(ZoneOffset.UTC),NOW.minusHours(1).atOffset(ZoneOffset.UTC),1,20),"COMMON-1001",400);}
 private AuditLog log(Long id,String detail){return new AuditLog(id,7L,2L,"OUTBOUND","ORDER",9L,"SUCCESS",detail,NOW,NOW);}
 private void assertCode(org.assertj.core.api.ThrowableAssert.ThrowingCallable call,String code,int status){assertThatThrownBy(call).isInstanceOf(AuditQueryException.class).satisfies(e->{assertThat(((AuditQueryException)e).code()).isEqualTo(code);assertThat(((AuditQueryException)e).status()).isEqualTo(status);});}
}
