package com.shipflow.audit.application;
import com.fasterxml.jackson.databind.*; import com.fasterxml.jackson.databind.node.*; import com.shipflow.audit.api.model.*; import com.shipflow.audit.domain.AuditLog; import com.shipflow.audit.mapper.AuditQueryMapper; import org.springframework.stereotype.Service; import java.time.*; import java.util.*;
@Service public class AuditQueryApplicationService {
 private static final Set<String> SENSITIVE=Set.of("password","passwordhash","temporarypassword","token","refreshtoken","jwt","hmac","secret","credential","authorization","address","addressline1","addressline2","phone","email","contactname");
 private final AuditQueryMapper mapper; private final ObjectMapper json; public AuditQueryApplicationService(AuditQueryMapper mapper,ObjectMapper json){this.mapper=mapper;this.json=json;}
 public AuditLogPageResponse list(Long tenantId,String resourceType,Long resourceId,String action,Long operatorId,OffsetDateTime from,OffsetDateTime to,int page,int pageSize){tenant(tenantId);page(page,pageSize);if(from!=null&&to!=null&&from.isAfter(to))throw bad();String type=text(resourceType),act=text(action);long total=mapper.count(tenantId,type,resourceId,act,operatorId,utc(from),utc(to));return new AuditLogPageResponse(page,pageSize,(total+pageSize-1)/pageSize,total,mapper.findPage(tenantId,type,resourceId,act,operatorId,utc(from),utc(to),(page-1)*pageSize,pageSize).stream().map(this::response).toList());}
 public AuditLogResponse get(Long tenantId,Long auditId){tenant(tenantId);AuditLog value=mapper.findById(tenantId,auditId);if(value==null)throw notFound();return response(value);}
 public AuditLogPageResponse listPlatform(Long targetTenantId,String resourceType,Long resourceId,String action,Long operatorId,OffsetDateTime from,OffsetDateTime to,int page,int pageSize){if(targetTenantId==null||!mapper.tenantExists(targetTenantId))throw notFound();return list(targetTenantId,resourceType,resourceId,action,operatorId,from,to,page,pageSize);}
 public AuditLogResponse getPlatform(Long targetTenantId,Long auditId){if(targetTenantId==null||!mapper.tenantExists(targetTenantId))throw notFound();return get(targetTenantId,auditId);}
 private AuditLogResponse response(AuditLog a){return new AuditLogResponse(a.id(),a.tenantId(),a.operatorUserId(),a.actionType(),a.resourceType(),a.resourceId(),a.resultStatus(),sanitize(a.detail()),offset(a.occurredAt()),offset(a.createdAt()));}
 private Map<String,Object> sanitize(String raw){if(raw==null||raw.isBlank())return Map.of();try{JsonNode node=json.readTree(raw);JsonNode clean=clean(node,null);if(clean.isObject())return json.convertValue(clean,new com.fasterxml.jackson.core.type.TypeReference<LinkedHashMap<String,Object>>(){});return Map.of("value",clean.asText());}catch(Exception e){return Map.of("redacted",true);}}
 private JsonNode clean(JsonNode node,String key){if(key!=null&&sensitive(key))return TextNode.valueOf("[REDACTED]");if(node.isObject()){ObjectNode result=json.createObjectNode();node.fields().forEachRemaining(e->result.set(e.getKey(),clean(e.getValue(),e.getKey())));return result;}if(node.isArray()){ArrayNode result=json.createArrayNode();node.forEach(v->result.add(clean(v,null)));return result;}if(node.isTextual()&&looksSensitive(node.asText()))return TextNode.valueOf("[REDACTED]");return node;}
 private boolean sensitive(String key){return SENSITIVE.contains(key.replaceAll("[^A-Za-z0-9]","").toLowerCase(Locale.ROOT))||key.toLowerCase(Locale.ROOT).contains("address");} private boolean looksSensitive(String value){return value.matches("(?s).*eyJ[a-zA-Z0-9_-]{10,}.*")||value.toLowerCase(Locale.ROOT).contains("bearer ");}
 private String text(String value){if(value==null||value.isBlank())return null;String v=value.trim();if(v.length()>64)throw bad();return v;} private LocalDateTime utc(OffsetDateTime value){return value==null?null:LocalDateTime.ofInstant(value.toInstant(),ZoneOffset.UTC);} private OffsetDateTime offset(LocalDateTime value){return value==null?null:value.atOffset(ZoneOffset.UTC);} private void tenant(Long id){if(id==null||id<1)throw new AuditQueryException("COMMON-1004",403);} private void page(int p,int s){if(p<1||s<1||s>100)throw bad();} private AuditQueryException bad(){return new AuditQueryException("COMMON-1001",400);} private AuditQueryException notFound(){return new AuditQueryException("COMMON-1006",404);}
}
