package com.shipflow.store.application;
import com.shipflow.store.api.model.*; import com.shipflow.store.domain.model.*; import com.shipflow.store.mapper.*; import org.springframework.dao.DuplicateKeyException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.time.*; import java.util.HexFormat;
@Service public class StoreApplicationService { private final StoreMapper mapper; private final StoreIdempotencyMapper idem; private final StoreAuditMapper audit; private final Clock clock; public StoreApplicationService(StoreMapper m,StoreIdempotencyMapper i,StoreAuditMapper a,Clock c){mapper=m;idem=i;audit=a;clock=c;}
 @Transactional public Store create(Long t,CreateStoreRequest r,String key,Long op,String req){checkKey(key); String h=hash(r.storeCode()+"\n"+r.storeName()+"\n"+r.platformCode()+"\n"+r.platformAccount()); var prior=idem.find(t,"createStore",key); if(prior!=null){if(!h.equals(prior.requestHash()))throw new StoreException("COMMON-1009",409); if(prior.resourceId()!=null)return required(t,prior.resourceId());throw new StoreException("COMMON-1010",409);} try{idem.insert(t,"createStore",key,h,LocalDateTime.now(clock).plusMinutes(30)); if(mapper.findByCode(t,r.storeCode())!=null||mapper.findByAccount(t,r.platformCode(),r.platformAccount())!=null)throw new StoreException("STORE-1001",409); mapper.insert(new Store(null,t,r.storeCode(),r.storeName(),r.platformCode(),r.platformAccount(),"ACTIVE",0,null,null)); Store s=mapper.findByCode(t,r.storeCode()); if(s==null)throw new IllegalStateException("Store was not created"); idem.complete(t,"createStore",key,s.id()); audit.insert(t,op,"CREATE",s.id(),req,LocalDateTime.now(clock)); return s;}catch(DuplicateKeyException e){throw new StoreException("STORE-1001",409);}}
 public StorePage page(Long t,String status,String platform,int p,int n){if(p<1||n<1||n>100)throw new StoreException("COMMON-1001",400);long total=mapper.count(t,status,platform);return new StorePage(p,n,total,(int)((total+n-1)/n),mapper.page(t,status,platform,(p-1)*n,n));}
 public Store get(Long t,Long id){return required(t,id);}
 @Transactional public Store update(Long t,Long id,UpdateStoreRequest r,Long op,String req){Store existing=required(t,id); Store duplicate=mapper.findByAccount(t,r.platformCode(),r.platformAccount()); if(duplicate!=null&&!duplicate.id().equals(existing.id()))throw new StoreException("STORE-1001",409); if(mapper.update(t,id,r.storeName(),r.platformCode(),r.platformAccount(),r.version())!=1)throw conflict(t,id);Store s=required(t,id);audit.insert(t,op,"UPDATE",id,req,LocalDateTime.now(clock));return s;}
 @Transactional public Store status(Long t,Long id,StoreStatusChangeRequest r,Long op,String req){if(!"ACTIVE".equals(r.status())&&!"DISABLED".equals(r.status()))throw new StoreException("STORE-1002",422);if(mapper.updateStatus(t,id,r.status(),r.version())!=1)throw conflict(t,id);Store s=required(t,id);audit.insert(t,op,"STATUS_CHANGE",id,req,LocalDateTime.now(clock));return s;}
 private Store required(Long t,Long id){Store s=mapper.findById(t,id);if(s==null)throw new StoreException("COMMON-1006",404);return s;} private StoreException conflict(Long t,Long id){return mapper.findById(t,id)==null?new StoreException("COMMON-1006",404):new StoreException("COMMON-1005",409);} private void checkKey(String k){if(k==null||k.isBlank()||k.length()>128)throw new StoreException("COMMON-1001",400);} private String hash(String v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
