package com.shipflow.exceptioncase;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.shipflow.exceptioncase.api.model.*;
import com.shipflow.exceptioncase.application.*;
import com.shipflow.exceptioncase.domain.*;
import com.shipflow.exceptioncase.mapper.ExceptionClaimMapper;
import org.junit.jupiter.api.*;
import java.math.BigDecimal;
import java.time.*;
import java.util.List;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

class ExceptionClaimApplicationServiceTest {
 private static final LocalDateTime NOW=LocalDateTime.of(2026,8,11,12,0);
 private ExceptionClaimMapper mapper; private ExceptionClaimApplicationService service;
 @BeforeEach void setUp(){mapper=mock(ExceptionClaimMapper.class);service=new ExceptionClaimApplicationService(mapper,new ObjectMapper(),Clock.fixed(NOW.toInstant(ZoneOffset.UTC),ZoneOffset.UTC));}

 @Test void listsOnlyCurrentTenantAndReturnsPage(){when(mapper.countExceptions(7L,null,"OPEN")).thenReturn(1L);when(mapper.findExceptions(7L,null,"OPEN",0,20)).thenReturn(List.of(exception(1L,"OPEN",0L,null)));var page=service.list(7L,null,"open",1,20);assertThat(page.total()).isEqualTo(1);assertThat(page.items()).extracting(ExceptionCaseResponse::id).containsExactly(1L);verify(mapper).findExceptions(7L,null,"OPEN",0,20);}
 @Test void crossTenantOrMissingExceptionIsUniformNotFound(){when(mapper.findException(7L,9L)).thenReturn(null);assertCode(()->service.get(7L,9L),"COMMON-1006",404);}
 @Test void createsExceptionFromTenantTrackingEventAndAudits(){when(mapper.orderExists(7L,9L)).thenReturn(true);when(mapper.trackingEventExists(7L,9L,5L)).thenReturn(true);when(mapper.findExceptionByNo(eq(7L),anyString())).thenReturn(exception(11L,"OPEN",0L,null));var result=service.createException(7L,2L,9L,new CreateExceptionRequest("transport","late",OffsetDateTime.parse("2026-08-11T11:00:00Z"),5L),"key-1","req-1");assertThat(result.id()).isEqualTo(11L);verify(mapper).insertException(eq(7L),eq(9L),anyString(),eq("TRANSPORT"),eq("late"),eq(LocalDateTime.of(2026,8,11,11,0)));verify(mapper).insertAudit(eq(7L),eq(2L),eq("EXCEPTION_CREATE"),eq("EXCEPTION_CASE"),eq(11L),eq("req-1"),isNull(),contains("trackingEventId"),eq(NOW));verify(mapper).completeIdempotency(7L,"createExceptionCase","key-1","EXCEPTION_CASE",11L);}
 @Test void repeatedCreateReturnsOriginalWithoutDuplicateWrites(){when(mapper.findIdempotency(7L,"createExceptionCase","key-1")).thenReturn(new ExceptionClaimMapper.IdempotencyRecord(hashException(),11L));when(mapper.findException(7L,11L)).thenReturn(exception(11L,"OPEN",0L,null));var result=service.createException(7L,2L,9L,new CreateExceptionRequest("transport","late",OffsetDateTime.parse("2026-08-11T11:00:00Z"),5L),"key-1",null);assertThat(result.id()).isEqualTo(11L);verify(mapper,never()).insertException(any(),any(),any(),any(),any(),any());verify(mapper,never()).insertAudit(any(),any(),any(),any(),any(),any(),any(),any(),any());}
 @Test void assignmentMovesOpenToProcessing(){when(mapper.findException(7L,11L)).thenReturn(exception(11L,"OPEN",0L,null),exception(11L,"PROCESSING",1L,8L));when(mapper.activeTenantUserExists(7L,8L)).thenReturn(true);when(mapper.transitionException(7L,11L,"OPEN","PROCESSING",0L)).thenReturn(1);var assigned=service.assign(7L,2L,11L,new AssignExceptionRequest(8L,"owner",0L),null);assertThat(assigned.status()).isEqualTo("PROCESSING");assertThat(assigned.assignedToUserId()).isEqualTo(8L);verify(mapper).insertAudit(eq(7L),eq(2L),eq("EXCEPTION_ASSIGN"),any(),eq(11L),isNull(),eq("owner"),contains("assignedToUserId"),eq(NOW));}
 @Test void repeatedAssignmentIsRejectedWithoutAnotherTransitionOrAudit(){when(mapper.findException(7L,11L)).thenReturn(exception(11L,"PROCESSING",1L,8L));when(mapper.activeTenantUserExists(7L,8L)).thenReturn(true);assertCode(()->service.assign(7L,2L,11L,new AssignExceptionRequest(8L,"again",1L),null),"EXCEPTION-1002",409);verify(mapper,never()).transitionException(any(),any(),any(),any(),any());verify(mapper,never()).insertAudit(any(),any(),any(),any(),any(),any(),any(),any(),any());}
 @Test void illegalExceptionJumpAndDuplicateAreRejected(){when(mapper.findException(7L,11L)).thenReturn(exception(11L,"OPEN",0L,null));assertCode(()->service.transitionException(7L,2L,11L,new ExceptionStatusRequest("RESOLVED","skip",0L),null),"EXCEPTION-1002",409);verify(mapper,never()).transitionException(any(),any(),any(),any(),any());}
 @Test void claimRequiresResolvedEligibleException(){when(mapper.findClaimEligibility(7L,11L)).thenReturn(new ClaimEligibility(11L,"PROCESSING","IN_TRANSIT","USD"));assertCode(()->service.createClaim(7L,2L,11L,new CreateClaimRequest(new BigDecimal("10.00"),"USD"),"claim-key",null),"CLAIM-1001",422);verify(mapper,never()).insertClaim(any(),any(),any(),any(),any());}
 @Test void createsEligibleClaim(){when(mapper.findClaimEligibility(7L,11L)).thenReturn(new ClaimEligibility(11L,"RESOLVED","DELIVERED","USD"));when(mapper.findClaimByException(7L,11L)).thenReturn(null);when(mapper.findClaimByNo(eq(7L),anyString())).thenReturn(claim(21L,"OPEN",0L));var result=service.createClaim(7L,2L,11L,new CreateClaimRequest(new BigDecimal("10.00"),"USD"),"claim-key",null);assertThat(result.id()).isEqualTo(21L);verify(mapper).insertClaim(eq(7L),eq(11L),anyString(),eq(new BigDecimal("10.00")),eq("USD"));verify(mapper).completeIdempotency(7L,"createClaimRecord","claim-key","CLAIM_RECORD",21L);}
 @Test void existingClaimIsRejectedWithoutDuplicateInsert(){when(mapper.findClaimEligibility(7L,11L)).thenReturn(new ClaimEligibility(11L,"RESOLVED","DELIVERED","USD"));when(mapper.findClaimByException(7L,11L)).thenReturn(claim(21L,"OPEN",0L));assertCode(()->service.createClaim(7L,2L,11L,new CreateClaimRequest(new BigDecimal("10.00"),"USD"),"second-key",null),"CLAIM-1002",409);verify(mapper,never()).insertClaim(any(),any(),any(),any(),any());verify(mapper,never()).insertAudit(any(),any(),any(),any(),any(),any(),any(),any(),any());}
 @Test void claimCannotSkipSubmission(){when(mapper.findClaim(7L,21L)).thenReturn(claim(21L,"OPEN",0L));assertCode(()->service.resolveClaim(7L,2L,21L,new ClaimResultRequest("APPROVED","ok",OffsetDateTime.parse("2026-08-11T12:00:00Z"),0L),null),"CLAIM-1004",409);}
 @Test void submitsApprovesAndClosesAlongForwardPath(){when(mapper.findClaim(7L,21L)).thenReturn(claim(21L,"OPEN",0L),claim(21L,"SUBMITTED",1L),claim(21L,"SUBMITTED",1L),claim(21L,"APPROVED",2L),claim(21L,"APPROVED",2L),claim(21L,"CLOSED",3L));when(mapper.transitionClaim(anyLong(),anyLong(),anyString(),anyString(),anyLong(),any(),any())).thenReturn(1);assertThat(service.submitClaim(7L,2L,21L,new ClaimActionRequest("submit",0L),null).status()).isEqualTo("SUBMITTED");assertThat(service.resolveClaim(7L,2L,21L,new ClaimResultRequest("APPROVED","approve",OffsetDateTime.parse("2026-08-11T12:00:00Z"),1L),null).status()).isEqualTo("APPROVED");assertThat(service.closeClaim(7L,2L,21L,new ClaimActionRequest("close",2L),null).status()).isEqualTo("CLOSED");}

 private ExceptionCase exception(Long id,String status,Long version,Long assignee){return new ExceptionCase(id,7L,9L,"EX1","TRANSPORT",status,"late",NOW.minusHours(1),version,NOW.minusHours(1),NOW,assignee);}
 private ClaimRecord claim(Long id,String status,Long version){return new ClaimRecord(id,7L,11L,"CL1",status,new BigDecimal("10.00"),"USD",null,null,version,NOW,NOW);}
 private void assertCode(org.assertj.core.api.ThrowableAssert.ThrowingCallable call,String code,int status){assertThatThrownBy(call).isInstanceOf(ExceptionClaimException.class).satisfies(e->{assertThat(((ExceptionClaimException)e).code()).isEqualTo(code);assertThat(((ExceptionClaimException)e).status()).isEqualTo(status);});}
 private String hashException(){try{return java.util.HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest("9\nTRANSPORT\nlate\n2026-08-11T11:00:00Z\n5".getBytes(java.nio.charset.StandardCharsets.UTF_8)));}catch(Exception e){throw new AssertionError(e);}}
}
