package com.shipflow.exceptioncase;

import com.shipflow.common.exception.GlobalExceptionHandler;
import com.shipflow.exceptioncase.api.ExceptionClaimController;
import com.shipflow.exceptioncase.api.model.*;
import com.shipflow.exceptioncase.application.*;
import com.shipflow.security.SecurityConfig;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.context.annotation.*;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.oauth2.jwt.JwtDecoder;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.mock.web.MockMultipartFile;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.List;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@WebMvcTest(ExceptionClaimController.class)
@Import({SecurityConfig.class,GlobalExceptionHandler.class,ExceptionClaimControllerWebMvcTest.Config.class})
class ExceptionClaimControllerWebMvcTest {
 @Autowired MockMvc mvc; @MockBean ExceptionClaimApplicationService service;
 @TestConfiguration static class Config{@Bean JwtDecoder jwtDecoder(){return token->{throw new org.springframework.security.oauth2.jwt.BadJwtException("test");};}}

 @Test void listsByJwtTenant()throws Exception{when(service.list(7L,2L,9L,"OPEN",null,null,null,null,null,null,null,1,20,"createdAt","DESC")).thenReturn(new ExceptionCasePageResponse(1,20,1,1,List.of(exception())));mvc.perform(get("/api/v1/exceptions").param("orderId","9").param("status","OPEN").with(readToken())).andExpect(status().isOk()).andExpect(jsonPath("$.data.items[0].id").value(11));verify(service).list(7L,2L,9L,"OPEN",null,null,null,null,null,null,null,1,20,"createdAt","DESC");}
 @Test void forwardsScopedFollowUpFilter()throws Exception{when(service.list(7L,2L,null,null,"PENDING_FOLLOW_UP",null,null,null,null,null,null,1,20,"createdAt","DESC")).thenReturn(new ExceptionCasePageResponse(1,20,0,0,List.of()));mvc.perform(get("/api/v1/exceptions").param("workbenchFilter","PENDING_FOLLOW_UP").with(readToken())).andExpect(status().isOk());verify(service).list(7L,2L,null,null,"PENDING_FOLLOW_UP",null,null,null,null,null,null,1,20,"createdAt","DESC");}
 @Test void crossTenantOrMissingDetailIsUniform404()throws Exception{when(service.get(7L,2L,11L)).thenThrow(new ExceptionClaimException("COMMON-1006",404));mvc.perform(get("/api/v1/exceptions/11").with(readToken())).andExpect(status().isNotFound()).andExpect(jsonPath("$.error.code").value("COMMON-1006"));}
 @Test void createsExceptionWithPermissionCsrfAndIdempotency()throws Exception{when(service.createException(eq(7L),eq(2L),eq(9L),any(),eq("key-1"),isNull())).thenReturn(exception());mvc.perform(post("/api/v1/orders/9/exceptions").with(writeToken()).with(csrf()).header("Idempotency-Key","key-1").contentType("application/json").content("{\"exceptionType\":\"TRANSPORT\",\"description\":\"late\",\"reportedAt\":\"2026-08-11T11:00:00Z\",\"trackingEventId\":5}" )).andExpect(status().isCreated()).andExpect(jsonPath("$.data.status").value("OPEN"));}
 @Test void writeWithoutExceptionManageIsForbidden()throws Exception{mvc.perform(post("/api/v1/orders/9/exceptions").with(readToken()).with(csrf()).header("Idempotency-Key","key-1").contentType("application/json").content("{\"exceptionType\":\"TRANSPORT\",\"description\":\"late\",\"reportedAt\":\"2026-08-11T11:00:00Z\"}" )).andExpect(status().isForbidden()).andExpect(jsonPath("$.error.code").value("COMMON-1004"));verifyNoInteractions(service);}
 @Test void assignmentRouteUsesTenantAndOperator()throws Exception{when(service.assign(eq(7L),eq(2L),eq(11L),any(),eq("assign-key"),eq("req-1"))).thenReturn(exception());mvc.perform(post("/api/v1/exceptions/11/assign").with(writeToken()).with(csrf()).header("Idempotency-Key","assign-key").header("X-Request-Id","req-1").header("X-Trace-Id","trace-assign-1").contentType("application/json").content("{\"assignedToUserId\":8,\"responsibleParty\":\"PROVIDER\",\"reason\":\"owner\",\"version\":0}" )).andExpect(status().isOk()).andExpect(header().string("X-Trace-Id","trace-assign-1")).andExpect(jsonPath("$.traceId").value("trace-assign-1"));verify(service).assign(eq(7L),eq(2L),eq(11L),any(),eq("assign-key"),eq("req-1"));}
 @Test void missingIdempotencyHeaderIsBadRequest()throws Exception{mvc.perform(post("/api/v1/exceptions/11/assign").with(writeToken()).with(csrf()).contentType("application/json").content("{\"assignedToUserId\":8,\"responsibleParty\":\"PROVIDER\",\"reason\":\"owner\",\"version\":0}" )).andExpect(status().isBadRequest()).andExpect(jsonPath("$.error.code").value("COMMON-1001"));verifyNoInteractions(service);}
 @Test void claimEligibilityErrorUsesUnified422()throws Exception{when(service.createClaim(eq(7L),eq(2L),eq(11L),any(),eq("claim-key"),isNull())).thenThrow(new ExceptionClaimException("CLAIM-1001",422));mvc.perform(post("/api/v1/exceptions/11/claim").with(writeToken()).with(csrf()).header("Idempotency-Key","claim-key").contentType("application/json").content("{\"claimAmount\":10.00,\"currency\":\"USD\",\"claimReason\":\"lost\",\"exceptionVersion\":0,\"evidenceAttachmentIds\":[]}" )).andExpect(status().isUnprocessableEntity()).andExpect(jsonPath("$.error.code").value("CLAIM-1001"));}
 @Test void handlingRecordRouteRequiresIdempotencyAndUsesTenantOperator()throws Exception{when(service.addHandlingRecord(eq(7L),eq(2L),eq(11L),any(),eq("handling-key"),isNull())).thenReturn(new HandlingRecordResponse(31L,11L,"EH1",2L,"FOLLOW_UP","contacted",OffsetDateTime.parse("2026-08-11T12:00:00Z")));mvc.perform(post("/api/v1/exceptions/11/handling-records").with(writeToken()).with(csrf()).header("Idempotency-Key","handling-key").contentType("application/json").content("{\"recordType\":\"FOLLOW_UP\",\"content\":\"contacted\",\"version\":0}" )).andExpect(status().isCreated()).andExpect(jsonPath("$.data.id").value(31));}
 @Test void evidenceUploadAcceptsMultipartDescriptionAndTrace()throws Exception{MockMultipartFile file=new MockMultipartFile("file","proof.pdf","application/pdf",new byte[]{1,2,3});MockMultipartFile description=new MockMultipartFile("description","","text/plain","delivery proof".getBytes());when(service.uploadEvidence(eq(7L),eq(2L),eq(11L),any(),eq("delivery proof"),eq(4L),eq("evidence-key"),eq("req-evidence"))).thenReturn(new EvidenceAttachmentResponse(41L,11L,2L,"proof.pdf","application/pdf",3L,"hash","delivery proof",OffsetDateTime.parse("2026-08-11T12:00:00Z")));mvc.perform(multipart("/api/v1/exceptions/11/evidence").file(file).file(description).param("version","4").with(writeToken()).with(csrf()).header("Idempotency-Key","evidence-key").header("X-Request-Id","req-evidence").header("X-Trace-Id","trace-evidence")).andExpect(status().isCreated()).andExpect(header().string("X-Trace-Id","trace-evidence")).andExpect(jsonPath("$.traceId").value("trace-evidence")).andExpect(jsonPath("$.data.description").value("delivery proof"));}
 @Test void octetStreamIsNotAcceptedAsEvidenceUpload()throws Exception{mvc.perform(post("/api/v1/exceptions/11/evidence").with(writeToken()).with(csrf()).header("Idempotency-Key","evidence-key").contentType("application/octet-stream").content("not-a-multipart-request")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.error.code").value("COMMON-1001"));verifyNoInteractions(service);}
 @Test void claimSubmitResultFinanceAndCloseRoutesRequireIdempotency()throws Exception{ClaimResponse claim=claim();when(service.submitClaim(eq(7L),eq(2L),eq(21L),any(),eq("submit-key"),isNull())).thenReturn(claim);when(service.resolveClaim(eq(7L),eq(2L),eq(21L),any(),eq("result-key"),isNull())).thenReturn(claim);when(service.financeConfirmClaim(eq(7L),eq(2L),eq(21L),any(),eq("finance-key"),isNull())).thenReturn(claim);when(service.closeClaim(eq(7L),eq(2L),eq(21L),any(),eq("close-key"),isNull())).thenReturn(claim);mvc.perform(post("/api/v1/claims/21/submit").with(writeToken()).with(csrf()).header("Idempotency-Key","submit-key").contentType("application/json").content("{\"reason\":\"submit\",\"version\":0}" )).andExpect(status().isOk());mvc.perform(post("/api/v1/claims/21/result").with(writeToken()).with(csrf()).header("Idempotency-Key","result-key").contentType("application/json").content("{\"status\":\"APPROVED\",\"reason\":\"ok\",\"approvedAmount\":10.00,\"resolvedAt\":\"2026-08-11T12:00:00Z\",\"version\":1}" )).andExpect(status().isOk());mvc.perform(post("/api/v1/claims/21/finance-confirmation").with(writeToken()).with(csrf()).header("Idempotency-Key","finance-key").contentType("application/json").content("{\"reason\":\"checked\",\"version\":2}" )).andExpect(status().isOk());mvc.perform(post("/api/v1/claims/21/close").with(writeToken()).with(csrf()).header("Idempotency-Key","close-key").contentType("application/json").content("{\"reason\":\"done\",\"version\":3}" )).andExpect(status().isOk());}
 @Test void claimWriteWithoutIdempotencyHeaderIsBadRequest()throws Exception{mvc.perform(post("/api/v1/claims/21/submit").with(writeToken()).with(csrf()).contentType("application/json").content("{\"reason\":\"submit\",\"version\":0}" )).andExpect(status().isBadRequest()).andExpect(jsonPath("$.error.code").value("COMMON-1001"));verifyNoInteractions(service);}
 @Test void unauthenticatedQueryIs401()throws Exception{mvc.perform(get("/api/v1/exceptions")).andExpect(status().isUnauthorized());}

 private org.springframework.test.web.servlet.request.RequestPostProcessor readToken(){return jwt().jwt(j->j.subject("2").claim("tenant_id","7")).authorities(new SimpleGrantedAuthority("scope:TENANT"),new SimpleGrantedAuthority("exception:read"));}
 private org.springframework.test.web.servlet.request.RequestPostProcessor writeToken(){return jwt().jwt(j->j.subject("2").claim("tenant_id","7")).authorities(new SimpleGrantedAuthority("scope:TENANT"),new SimpleGrantedAuthority("exception:manage"));}
 private ExceptionCaseResponse exception(){return new ExceptionCaseResponse(11L,9L,"EX1","TRANSPORT","OPEN","late",OffsetDateTime.parse("2026-08-11T11:00:00Z"),null,0L,OffsetDateTime.parse("2026-08-11T11:00:00Z"),OffsetDateTime.parse("2026-08-11T11:00:00Z"),null);}
 private ClaimResponse claim(){return new ClaimResponse(21L,11L,"CL1","SUBMITTED",new BigDecimal("10.00"),"USD",OffsetDateTime.parse("2026-08-11T12:00:00Z"),null,1L,OffsetDateTime.parse("2026-08-11T11:00:00Z"),OffsetDateTime.parse("2026-08-11T12:00:00Z"));}
}
