package com.shipflow.exceptioncase;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.shipflow.exceptioncase.api.model.*;
import com.shipflow.exceptioncase.application.*;
import com.shipflow.exceptioncase.domain.*;
import com.shipflow.exceptioncase.mapper.ExceptionClaimMapper;
import com.shipflow.store.mapper.StoreScopeMapper;
import org.junit.jupiter.api.*;
import java.math.BigDecimal;
import java.time.*;
import java.util.List;
import org.springframework.mock.web.MockMultipartFile;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

class ExceptionClaimApplicationServiceTest {
 private static final LocalDateTime NOW=LocalDateTime.of(2026,8,11,12,0);
 private ExceptionClaimMapper mapper; private StoreScopeMapper storeScope; private ExceptionClaimApplicationService service;
 @BeforeEach void setUp(){mapper=mock(ExceptionClaimMapper.class);storeScope=mock(StoreScopeMapper.class);when(storeScope.canAccessStore(any(),any(),any())).thenReturn(true);when(mapper.findException(anyLong(),anyLong())).thenAnswer(invocation -> ((Long)invocation.getArgument(1))==9L?null:exception((Long)invocation.getArgument(1),"OPEN",0L,null));service=new ExceptionClaimApplicationService(mapper,storeScope,new ObjectMapper(),Clock.fixed(NOW.toInstant(ZoneOffset.UTC),ZoneOffset.UTC));}

 @Test void listsOnlyCurrentTenantAndReturnsPage(){when(mapper.countAccessibleExceptions(7L,2L,null,"OPEN")).thenReturn(1L);when(mapper.findAccessibleExceptions(7L,2L,null,"OPEN",0,20)).thenReturn(List.of(exception(1L,"OPEN",0L,null)));var page=service.list(7L,2L,null,"open",1,20);assertThat(page.total()).isEqualTo(1);assertThat(page.items()).extracting(ExceptionCaseResponse::id).containsExactly(1L);verify(mapper).findAccessibleExceptions(7L,2L,null,"OPEN",0,20);}
 @Test void appliesFollowUpFilterInsideAccessibleStoreScope(){when(mapper.countAccessibleExceptions(7L,2L,null,null,"PENDING_FOLLOW_UP")).thenReturn(1L);when(mapper.findAccessibleExceptions(7L,2L,null,null,"PENDING_FOLLOW_UP",0,20)).thenReturn(List.of(exception(1L,"OPEN",0L,null)));var page=service.list(7L,2L,null,null,"pending_follow_up",1,20);assertThat(page.total()).isEqualTo(1);verify(mapper).countAccessibleExceptions(7L,2L,null,null,"PENDING_FOLLOW_UP");verify(mapper).findAccessibleExceptions(7L,2L,null,null,"PENDING_FOLLOW_UP",0,20);}
 @Test void filtersAndSortsByWhitelistedCreatedAt(){OffsetDateTime from=OffsetDateTime.parse("2026-08-01T00:00:00+08:00"),to=OffsetDateTime.parse("2026-08-20T00:00:00+08:00");when(mapper.countAccessibleExceptionsFiltered(eq(7L),eq(2L),isNull(),eq("OPEN"),isNull(),eq("TRANSPORT"),eq("SO-1"),eq(9L),eq("PROVIDER"),any(),any())).thenReturn(1L);when(mapper.findAccessibleExceptionsFiltered(eq(7L),eq(2L),isNull(),eq("OPEN"),isNull(),eq("TRANSPORT"),eq("SO-1"),eq(9L),eq("PROVIDER"),any(),any(),eq("CREATED_AT"),eq("DESC"),eq(0),eq(20))).thenReturn(List.of(exception(1L,"OPEN",0L,null)));var page=service.list(7L,2L,null,"open",null,"transport","SO-1",9L,"provider",from,to,1,20,"createdAt","desc");assertThat(page.total()).isEqualTo(1);verify(storeScope).canAccessStore(7L,2L,9L);}
 @Test void rejectsUnknownSortFieldAndDirection(){assertCode(()->service.list(7L,2L,null,null,null,null,null,null,null,null,null,1,20,"reportedAt","DESC"),"COMMON-1001",400);assertCode(()->service.list(7L,2L,null,null,null,null,null,null,null,null,null,1,20,"createdAt","DROP TABLE"),"COMMON-1001",400);}
 @Test void aggregatesDetailAndStableTimeline(){ExceptionCase detail=new ExceptionCase(11L,7L,9L,9L,"EX1","TRANSPORT","PROCESSING","late",NOW.minusHours(1),2L,NOW.minusHours(1),NOW,8L,"PROVIDER","SO-1","Tokyo Store","Owner");when(mapper.findException(7L,11L)).thenReturn(detail);when(mapper.findHandlingRecords(7L,2L,11L)).thenReturn(List.of(new HandlingRecord(31L,7L,11L,"EH1",2L,"FOLLOW_UP","called",NOW)));when(mapper.findEvidenceAttachments(7L,2L,11L)).thenReturn(List.of(new EvidenceAttachment(41L,7L,11L,2L,"proof.pdf","application/pdf",3L,"abc",null,"invoice",NOW)));when(mapper.findExceptionTimeline(7L,11L)).thenReturn(List.of(new ExceptionTimelineEvent(1L,"EXCEPTION_CREATE","Created","late",2L,"Operator","EXCEPTION_CASE",NOW.minusMinutes(5),null,"OPEN",11L,"req-1"),new ExceptionTimelineEvent(2L,"EXCEPTION_ASSIGN","Assigned","owner",2L,"Operator","EXCEPTION_CASE",NOW,"OPEN","PROCESSING",11L,"req-2")));var result=service.get(7L,2L,11L);assertThat(result.orderNo()).isEqualTo("SO-1");assertThat(result.storeName()).isEqualTo("Tokyo Store");assertThat(result.assignedToUserName()).isEqualTo("Owner");assertThat(result.handlingRecords()).hasSize(1);assertThat(result.evidenceAttachments()).extracting(EvidenceAttachmentResponse::description).containsExactly("invoice");assertThat(result.timeline()).extracting(ExceptionTimelineEventResponse::requestId).containsExactly("req-1","req-2");}
 @Test void crossTenantOrMissingExceptionIsUniformNotFound(){when(mapper.findException(7L,9L)).thenReturn(null);assertCode(()->service.get(7L,2L,9L),"COMMON-1006",404);}
 @Test void createsExceptionFromTenantTrackingEventAndAudits(){when(mapper.findOrderStoreId(7L,9L)).thenReturn(9L);when(mapper.orderExists(7L,9L)).thenReturn(true);when(mapper.trackingEventExists(7L,9L,5L)).thenReturn(true);when(mapper.findExceptionByNo(eq(7L),anyString())).thenReturn(exception(11L,"OPEN",0L,null));var result=service.createException(7L,2L,9L,new CreateExceptionRequest("transport","late",OffsetDateTime.parse("2026-08-11T11:00:00Z"),5L),"key-1","req-1");assertThat(result.id()).isEqualTo(11L);verify(mapper).insertException(eq(7L),eq(9L),anyString(),eq("TRANSPORT"),eq("late"),eq(LocalDateTime.of(2026,8,11,11,0)));verify(mapper).insertAudit(eq(7L),eq(2L),eq("EXCEPTION_CREATE"),eq("EXCEPTION_CASE"),eq(11L),eq("req-1"),isNull(),contains("trackingEventId"),eq(NOW));verify(mapper).completeIdempotency(7L,"createExceptionCase","key-1","EXCEPTION_CASE",11L);}
 @Test void repeatedCreateReturnsOriginalWithoutDuplicateWrites(){when(mapper.findIdempotency(7L,"createExceptionCase","key-1")).thenReturn(new ExceptionClaimMapper.IdempotencyRecord(hashException(),11L));when(mapper.findException(7L,11L)).thenReturn(exception(11L,"OPEN",0L,null));var result=service.createException(7L,2L,9L,new CreateExceptionRequest("transport","late",OffsetDateTime.parse("2026-08-11T11:00:00Z"),5L),"key-1",null);assertThat(result.id()).isEqualTo(11L);verify(mapper,never()).insertException(any(),any(),any(),any(),any(),any());verify(mapper,never()).insertAudit(any(),any(),any(),any(),any(),any(),any(),any(),any());}
 @Test void assignmentMovesOpenToProcessing(){when(mapper.findException(7L,11L)).thenReturn(exception(11L,"OPEN",0L,null),exception(11L,"PROCESSING",1L,8L));when(mapper.activeTenantUserExists(7L,8L)).thenReturn(true);when(mapper.assignException(7L,11L,0L,8L,"OTHER")).thenReturn(1);var assigned=service.assign(7L,2L,11L,new AssignExceptionRequest(8L,"OTHER","owner",0L),"assign-key",null);assertThat(assigned.status()).isEqualTo("PROCESSING");assertThat(assigned.assignedToUserId()).isEqualTo(8L);verify(mapper).insertAudit(eq(7L),eq(2L),eq("EXCEPTION_ASSIGN"),any(),eq(11L),anyString(),eq("owner"),contains("assignedToUserId"),eq(NOW));}
 @Test void repeatedAssignmentIsRejectedWithoutAnotherTransitionOrAudit(){when(mapper.findException(7L,11L)).thenReturn(exception(11L,"CLOSED",1L,8L));when(mapper.activeTenantUserExists(7L,8L)).thenReturn(true);assertCode(()->service.assign(7L,2L,11L,new AssignExceptionRequest(8L,"OTHER","again",1L),"assign-key",null),"EXCEPTION-1002",409);verify(mapper,never()).assignException(any(),any(),any(),any(),any());verify(mapper,never()).insertAudit(any(),any(),any(),any(),any(),any(),any(),any(),any());}
 @Test void illegalExceptionJumpAndDuplicateAreRejected(){when(mapper.findException(7L,11L)).thenReturn(exception(11L,"OPEN",0L,null));assertCode(()->service.transitionException(7L,2L,11L,new ExceptionStatusRequest("RESOLVED","skip",0L),"status-key",null),"EXCEPTION-1002",409);verify(mapper,never()).transitionException(any(),any(),any(),any(),any(),any());}
 @Test void claimRequiresEligibleOrderStatus(){when(mapper.findClaimEligibility(7L,11L)).thenReturn(new ClaimEligibility(11L,"PROCESSING","IN_TRANSIT","USD"));assertCode(()->service.createClaim(7L,2L,11L,claimRequest(),"claim-key",null),"CLAIM-1001",422);verify(mapper,never()).insertClaim(any(),any(),any(),any(),any(),any());}
 @Test void createsEligibleClaimAndMovesExceptionToFinancePending(){when(mapper.findClaimEligibility(7L,11L)).thenReturn(new ClaimEligibility(11L,"PROCESSING","DELIVERED","USD"));when(mapper.findClaimByException(7L,11L)).thenReturn(null);when(mapper.evidenceBelongsToException(7L,11L,41L)).thenReturn(true);when(mapper.transitionException(7L,11L,"OPEN","PENDING_FINANCE_CONFIRMATION",0L,null)).thenReturn(1);when(mapper.findClaimByNo(eq(7L),anyString())).thenReturn(claim(21L,"OPEN",0L));var result=service.createClaim(7L,2L,11L,claimRequest(),"claim-key",null);assertThat(result.id()).isEqualTo(21L);verify(mapper).insertClaim(eq(7L),eq(11L),anyString(),eq(new BigDecimal("10.00")),eq("USD"),eq("lost"));verify(mapper).insertClaimEvidenceReference(7L,21L,41L);verify(mapper).completeIdempotency(7L,"createClaimRecord","claim-key","CLAIM_RECORD",21L);}
 @Test void appendsHandlingRecordAndCompletesIdempotency(){when(mapper.touchException(7L,11L,0L)).thenReturn(1);when(mapper.findHandlingRecordByNo(eq(7L),eq(11L),anyString())).thenReturn(new HandlingRecord(31L,7L,11L,"EH1",2L,"FOLLOW_UP","provider contacted",NOW));var result=service.addHandlingRecord(7L,2L,11L,new CreateHandlingRecordRequest("FOLLOW_UP","provider contacted",0L),"handling-key",null);assertThat(result.id()).isEqualTo(31L);verify(mapper).insertHandlingRecord(eq(7L),eq(11L),anyString(),eq(2L),eq("FOLLOW_UP"),eq("provider contacted"),eq(NOW));verify(mapper).completeIdempotency(7L,"createExceptionHandlingRecord","handling-key","EXCEPTION_HANDLING_RECORD",31L);}
@Test void deduplicatesEvidenceByContentHashEvenWithDifferentFileName(){EvidenceAttachment existing=new EvidenceAttachment(41L,7L,11L,2L,"old.txt","text/plain",8L,"9e9d7f8f4f6c7c1e4f4e4a0b6d0c2d8f4b3a4a4b5c6d7e8f90123456789abcdef0",new byte[]{'e'},null,NOW);when(mapper.findEvidenceByHash(eq(7L),eq(11L),anyString())).thenReturn(existing);var result=service.uploadEvidence(7L,2L,11L,new MockMultipartFile("file","renamed.txt","text/plain",new byte[]{'e'}),"evidence-key",null);assertThat(result.id()).isEqualTo(41L);verify(mapper,never()).insertEvidence(any(),any(),any(),any(),any(),any(),any(),any(),any());verify(mapper).completeIdempotency(7L,"createExceptionEvidence","evidence-key","EXCEPTION_EVIDENCE_ATTACHMENT",41L);}
 @Test void existingClaimIsRejectedWithoutDuplicateInsert(){when(mapper.findClaimEligibility(7L,11L)).thenReturn(new ClaimEligibility(11L,"PROCESSING","DELIVERED","USD"));when(mapper.findClaimByException(7L,11L)).thenReturn(claim(21L,"OPEN",0L));assertCode(()->service.createClaim(7L,2L,11L,claimRequest(),"second-key",null),"CLAIM-1002",409);verify(mapper,never()).insertClaim(any(),any(),any(),any(),any(),any());verify(mapper,never()).insertAudit(any(),any(),any(),any(),any(),any(),any(),any(),any());}
 @Test void claimCannotSkipSubmission(){when(mapper.findClaim(7L,21L)).thenReturn(claim(21L,"OPEN",0L));assertCode(()->service.resolveClaim(7L,2L,21L,new ClaimResultRequest("APPROVED","ok",OffsetDateTime.parse("2026-08-11T12:00:00Z"),new BigDecimal("10.00"),0L),"result-key",null),"CLAIM-1004",409);}
 @Test void idempotencyConflictAndProcessingAreExplicit(){when(mapper.findIdempotency(7L,"assignExceptionCase","same-key")).thenReturn(new ExceptionClaimMapper.IdempotencyRecord("different",11L));assertCode(()->service.assign(7L,2L,11L,new AssignExceptionRequest(8L,"OTHER","owner",0L),"same-key",null),"COMMON-1009",409);reset(mapper);when(mapper.findException(7L,11L)).thenReturn(exception(11L,"OPEN",0L,null));when(mapper.findIdempotency(7L,"assignExceptionCase","processing-key")).thenReturn(new ExceptionClaimMapper.IdempotencyRecord(hash("11\n8\nOTHER\nowner\n0"),null));assertCode(()->service.assign(7L,2L,11L,new AssignExceptionRequest(8L,"OTHER","owner",0L),"processing-key",null),"COMMON-1010",409);}
 @Test void closedExceptionRejectsFurtherHandlingAndClaimMutation(){when(mapper.findException(7L,11L)).thenReturn(exception(11L,"CLOSED",5L,8L));assertCode(()->service.addHandlingRecord(7L,2L,11L,new CreateHandlingRecordRequest("FOLLOW_UP","late",5L),"h-closed",null),"EXCEPTION-1002",409);when(mapper.findClaim(7L,21L)).thenReturn(claim(21L,"SUBMITTED",1L));assertCode(()->service.resolveClaim(7L,2L,21L,new ClaimResultRequest("REJECTED","invalid",OffsetDateTime.parse("2026-08-11T12:00:00Z"),null,1L),"r-closed",null),"EXCEPTION-1002",409);}
 @Test void partialApprovalRequiresActualAmount(){when(mapper.findClaim(7L,21L)).thenReturn(claim(21L,"SUBMITTED",1L),claimWithFinance(21L,"PARTIALLY_APPROVED",2L,null));when(mapper.resolveClaim(7L,21L,"SUBMITTED","PARTIALLY_APPROVED",1L,new BigDecimal("4.50"),"damage",NOW)).thenReturn(1);var partial=service.resolveClaim(7L,2L,21L,new ClaimResultRequest("PARTIALLY_APPROVED","damage",OffsetDateTime.parse("2026-08-11T12:00:00Z"),new BigDecimal("4.50"),1L),"partial-key",null);assertThat(partial.status()).isEqualTo("PARTIALLY_APPROVED");}
 @Test void submitsApprovesFinanceConfirmsAndClosesAlongForwardPath(){ClaimRecord approved=claimWithFinance(21L,"APPROVED",2L,null);ClaimRecord confirmed=claimWithFinance(21L,"APPROVED",3L,NOW);when(mapper.findClaim(7L,21L)).thenReturn(claim(21L,"OPEN",0L),claim(21L,"SUBMITTED",1L),claim(21L,"SUBMITTED",1L),approved,approved,confirmed,confirmed,claim(21L,"CLOSED",4L));when(mapper.transitionClaim(anyLong(),anyLong(),anyString(),anyString(),anyLong(),any(),any())).thenReturn(1);when(mapper.resolveClaim(eq(7L),eq(21L),eq("SUBMITTED"),eq("APPROVED"),eq(1L),eq(new BigDecimal("10.00")),eq("approve"),eq(NOW))).thenReturn(1);when(mapper.financeConfirmClaim(7L,21L,2L,2L,NOW)).thenReturn(1);assertThat(service.submitClaim(7L,2L,21L,new ClaimActionRequest("submit",0L),"submit-key",null).status()).isEqualTo("SUBMITTED");assertThat(service.resolveClaim(7L,2L,21L,new ClaimResultRequest("APPROVED","approve",OffsetDateTime.parse("2026-08-11T12:00:00Z"),new BigDecimal("10.00"),1L),"result-key",null).status()).isEqualTo("APPROVED");assertThat(service.financeConfirmClaim(7L,2L,21L,new FinanceConfirmRequest("checked",2L),"finance-key",null).financeConfirmedAt()).isNotNull();assertThat(service.closeClaim(7L,2L,21L,new ClaimActionRequest("close",3L),"close-key",null).status()).isEqualTo("CLOSED");}

 private ExceptionCase exception(Long id,String status,Long version,Long assignee){return new ExceptionCase(id,7L,9L,"EX1","TRANSPORT",status,"late",NOW.minusHours(1),version,NOW.minusHours(1),NOW,assignee);}
 private ClaimRecord claim(Long id,String status,Long version){return new ClaimRecord(id,7L,11L,"CL1",status,new BigDecimal("10.00"),"USD",null,null,version,NOW,NOW);}
 private ClaimRecord claimWithFinance(Long id,String status,Long version,LocalDateTime confirmedAt){return new ClaimRecord(id,7L,11L,"CL1",status,new BigDecimal("10.00"),"USD",null,NOW,version,NOW,NOW,"lost",new BigDecimal("10.00"),"approve",confirmedAt==null?null:2L,confirmedAt==null?null:"Finance",confirmedAt);}
 private CreateClaimRequest claimRequest(){return new CreateClaimRequest(new BigDecimal("10.00"),"USD","lost",0L,List.of(41L));}
 private String hash(String value){try{return java.util.HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(value.getBytes(java.nio.charset.StandardCharsets.UTF_8)));}catch(Exception e){throw new AssertionError(e);}}
 private void assertCode(org.assertj.core.api.ThrowableAssert.ThrowingCallable call,String code,int status){assertThatThrownBy(call).isInstanceOf(ExceptionClaimException.class).satisfies(e->{assertThat(((ExceptionClaimException)e).code()).isEqualTo(code);assertThat(((ExceptionClaimException)e).status()).isEqualTo(status);});}
 private String hashException(){try{return java.util.HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest("9\nTRANSPORT\nlate\n2026-08-11T11:00:00Z\n5".getBytes(java.nio.charset.StandardCharsets.UTF_8)));}catch(Exception e){throw new AssertionError(e);}}
}
