package com.shipflow.store;
import com.shipflow.store.api.model.*; import com.shipflow.store.application.*; import com.shipflow.store.domain.model.Store; import com.shipflow.store.domain.model.StoreAddress; import com.shipflow.store.domain.model.StoreChannel; import com.shipflow.store.mapper.*; import org.junit.jupiter.api.*; import java.time.*; import java.util.List; import static org.assertj.core.api.Assertions.*; import static org.mockito.Mockito.*;
class StoreApplicationServiceTest { StoreMapper mapper=mock(StoreMapper.class); StoreIdempotencyMapper idem=mock(StoreIdempotencyMapper.class); StoreAuditMapper audit=mock(StoreAuditMapper.class); StoreApplicationService service=new StoreApplicationService(mapper,idem,audit,Clock.fixed(Instant.parse("2026-08-09T00:00:00Z"),ZoneOffset.UTC)); Store store=new Store(10L,1L,"S1","Name","P","acct","ACTIVE",0L,LocalDateTime.now(),LocalDateTime.now());
 StoreResourceMapper resources=mock(StoreResourceMapper.class); StoreScopeMapper scope=mock(StoreScopeMapper.class); StoreApplicationService configurableService=new StoreApplicationService(mapper,idem,audit,resources,scope,Clock.fixed(Instant.parse("2026-08-09T00:00:00Z"),ZoneOffset.UTC));
 @Test void createReplaysSameIdempotencyRequest(){when(idem.find(1L,"createStore","k")).thenReturn(new StoreIdempotencyMapper.Record("e30f7d5dc7d175d852826480fe63ddac2396ded3b7843d9540b52cc6bfed3273",10L));when(mapper.findById(1L,10L)).thenReturn(store);assertThat(service.create(1L,new CreateStoreRequest("S1","Name","P","acct"),"k",2L,null)).isEqualTo(store);verify(mapper,never()).insert(any());}
 @Test void differentIdempotencyBodyConflicts(){when(idem.find(1L,"createStore","k")).thenReturn(new StoreIdempotencyMapper.Record("other",10L));assertThatThrownBy(()->service.create(1L,new CreateStoreRequest("S1","Name","P","acct"),"k",2L,null)).isInstanceOf(StoreException.class).extracting(e->((StoreException)e).code()).isEqualTo("COMMON-1009");}
 @Test void merchantOperatorCannotReadUnauthorizedStore(){when(mapper.findByIdForUser(1L,2L,10L)).thenReturn(null);assertThatThrownBy(()->service.get(1L,2L,10L)).isInstanceOf(StoreException.class).extracting(e->((StoreException)e).code()).isEqualTo("COMMON-1006");}
 @Test void storeListUsesCallerScopedCountAndPage(){var item=new StoreListItem(10L,1L,"S1","Name","P",null,null,null,"ACTIVE",0L,null);when(mapper.countForUser(1L,2L,null,null,null,null,"updatedAt","DESC")).thenReturn(1L);when(mapper.pageForUser(1L,2L,null,null,null,null,"updatedAt","DESC",0,20)).thenReturn(List.of(item));var page=service.page(1L,2L,null,null,null,null,"updatedAt","DESC",1,20);assertThat(page.total()).isEqualTo(1L);assertThat(page.items()).containsExactly(item);verify(mapper).countForUser(1L,2L,null,null,null,null,"updatedAt","DESC");verify(mapper).pageForUser(1L,2L,null,null,null,null,"updatedAt","DESC",0,20);}
 @Test void storeListPassesSearchAndSortToScopedQueries(){var item=new StoreListItem(10L,1L,"S1","Name","P","CN","Shanghai / Line 1","SF / Express","ACTIVE",0L,null);when(mapper.countForUser(1L,2L,"S1","Name","P","ACTIVE","updatedAt","DESC")).thenReturn(1L);when(mapper.pageForUser(1L,2L,"S1","Name","P","ACTIVE","updatedAt","DESC",0,20)).thenReturn(List.of(item));var page=service.page(1L,2L,"S1","Name","P","ACTIVE","updatedAt","DESC",1,20);assertThat(page.items()).containsExactly(item);verify(mapper).countForUser(1L,2L,"S1","Name","P","ACTIVE","updatedAt","DESC");verify(mapper).pageForUser(1L,2L,"S1","Name","P","ACTIVE","updatedAt","DESC",0,20);}
 @Test void storeListRejectsUnsafeSortAndInvalidStatus(){assertThatThrownBy(()->service.page(1L,2L,null,null,null,"ACTIVE;DROP TABLE merchant_store","id","DESC",1,20)).isInstanceOf(StoreException.class).extracting(e->((StoreException)e).code()).isEqualTo("COMMON-1001");assertThatThrownBy(()->service.page(1L,2L,null,null,null,"PENDING","updatedAt","DESC",1,20)).isInstanceOf(StoreException.class).extracting(e->((StoreException)e).code()).isEqualTo("COMMON-1001");}
 @Test void invalidStatusIsRejected(){assertThatThrownBy(()->service.status(1L,2L,10L,new StoreStatusChangeRequest("PENDING",0L),null,null)).isInstanceOf(StoreException.class).extracting(e->((StoreException)e).code()).isEqualTo("STORE-1002");}
 @Test void storeDetailMasksPlatformAccountAndIncludesScopedHistoryAndAudit(){var auditSummary=new StoreAuditSummary("UPDATE","SUCCESS",LocalDateTime.of(2026,8,9,0,0));when(mapper.findByIdForUser(1L,2L,10L)).thenReturn(store);when(mapper.countHistoricalOrders(1L,10L)).thenReturn(3L);when(audit.findRecent(1L,10L,10)).thenReturn(List.of(auditSummary));var detail=service.getDetail(1L,2L,10L);assertThat(detail.platformAccountMasked()).isEqualTo("a**t");assertThat(detail.platformAccountMasked()).doesNotContain("acct");assertThat(detail.historicalOrderCount()).isEqualTo(3L);assertThat(detail.auditSummary()).containsExactly(auditSummary);assertThat(detail.unavailableFields()).containsExactly("countryRegion","defaultShippingAddress","defaultLogisticsChannel");verify(mapper).countHistoricalOrders(1L,10L);verify(audit).findRecent(1L,10L,10);}
 @Test void unauthorizedStoreDetailDoesNotQueryAggregates(){when(mapper.findByIdForUser(1L,2L,10L)).thenReturn(null);assertThatThrownBy(()->service.getDetail(1L,2L,10L)).isInstanceOf(StoreException.class).extracting(e->((StoreException)e).code()).isEqualTo("COMMON-1006");verify(mapper,never()).countHistoricalOrders(anyLong(),anyLong());verify(audit,never()).findRecent(anyLong(),anyLong(),anyInt());}
 @Test void detailReadsConfiguredAddressAndChannelFromScopedResources(){when(mapper.findByIdForUser(1L,2L,10L)).thenReturn(store);when(resources.findDefaultAddress(1L,10L)).thenReturn(new StoreAddress(21L,1L,10L,"A1","Name","Co","13812345678","x@example.com","CN",null,"Shanghai",null,"Line 1",null,"200000","ACTIVE",true,3L,2L,2L,null,null));when(resources.findDefaultChannel(1L,10L)).thenReturn(new StoreChannel(31L,1L,10L,41L,"SF","Express","Provider","ACTIVE",true,4L,2L,2L,null,null));when(resources.configurationVersion(1L,10L)).thenReturn(4L);when(mapper.countHistoricalOrders(1L,10L)).thenReturn(3L);when(audit.findRecent(1L,10L,10)).thenReturn(List.of());var detail=configurableService.getDetail(1L,2L,10L);assertThat(detail.countryRegion()).isEqualTo("CN");assertThat(detail.defaultShippingAddress()).contains("Shanghai").doesNotContain("13812345678");assertThat(detail.defaultLogisticsChannel()).contains("SF");assertThat(detail.unavailableFields()).isEmpty();assertThat(detail.configurationVersion()).isEqualTo(4L);}
 @Test void detailMarksEmptyConfiguredResourcesAsNotConfigured(){when(mapper.findByIdForUser(1L,2L,10L)).thenReturn(store);when(resources.findDefaultAddress(1L,10L)).thenReturn(null);when(resources.findDefaultChannel(1L,10L)).thenReturn(null);when(mapper.countHistoricalOrders(1L,10L)).thenReturn(0L);when(audit.findRecent(1L,10L,10)).thenReturn(List.of());var detail=configurableService.getDetail(1L,2L,10L);assertThat(detail.countryRegion()).isNull();assertThat(detail.defaultShippingAddress()).isNull();assertThat(detail.defaultLogisticsChannel()).isNull();assertThat(detail.unavailableFields()).isEmpty();}
 @Test void configurationWriteRequiresMerchantAdminScope(){when(mapper.findByIdForUser(1L,2L,10L)).thenReturn(store);when(scope.canManageStoreConfiguration(1L,2L,10L)).thenReturn(false);var request=new UpdateStoreAddressRequest("A1","Name",null,"13812345678",null,"CN",null,"Shanghai",null,"Line 1",null,"200000",0L);assertThatThrownBy(()->configurableService.updateDefaultAddress(1L,2L,10L,request,"key",null)).isInstanceOf(StoreException.class).extracting(e->((StoreException)e).code()).isEqualTo("COMMON-1004");verify(resources,never()).insertAddress(any());}
 @Test void updateReplaysSameIdempotencyRequestWithoutWritingAgain(){var request=new UpdateStoreRequest("Renamed","AMAZON","acct-2",0L);when(idem.find(1L,"updateStore","key")).thenReturn(new StoreIdempotencyMapper.Record(hash("10\nRenamed\nAMAZON\nacct-2\n0"),10L));when(mapper.findByIdForUser(1L,2L,10L)).thenReturn(store);var result=service.update(1L,2L,10L,request,"key",null);assertThat(result).isEqualTo(store);verify(mapper,never()).update(anyLong(),anyLong(),anyString(),anyString(),anyString(),anyLong());verify(audit,never()).insert(anyLong(),anyLong(),anyString(),anyLong(),anyString(),any());}
 @Test void updateRequiresIdempotencyKey(){assertThatThrownBy(()->service.update(1L,2L,10L,new UpdateStoreRequest("Renamed","AMAZON","acct-2",0L),null,null)).isInstanceOf(StoreException.class).extracting(e->((StoreException)e).code()).isEqualTo("COMMON-1001");}
 @Test void statusRejectsDifferentIdempotencyBody(){when(mapper.findByIdForUser(1L,2L,10L)).thenReturn(store);when(idem.find(1L,"changeStoreStatus","key")).thenReturn(new StoreIdempotencyMapper.Record("different",10L));assertThatThrownBy(()->service.status(1L,2L,10L,new StoreStatusChangeRequest("DISABLED",0L),"key",null)).isInstanceOf(StoreException.class).extracting(e->((StoreException)e).code()).isEqualTo("COMMON-1009");verify(mapper,never()).updateStatus(anyLong(),anyLong(),anyString(),anyLong());}
 @Test void merchantAdminCanEnableDisabledStoreWithStatusScope(){
  Store disabled=new Store(10L,1L,"S1","Name","P","acct","DISABLED",3L,LocalDateTime.now(),LocalDateTime.now());
  when(mapper.findByIdForUser(1L,2L,10L)).thenReturn(disabled);
  when(scope.canManageStoreStatus(1L,2L,10L)).thenReturn(true);
  when(idem.find(1L,"changeStoreStatus","key")).thenReturn(null);
  when(mapper.updateStatus(1L,10L,"ACTIVE",3L)).thenReturn(1);
  var result=configurableService.status(1L,2L,10L,new StoreStatusChangeRequest("ACTIVE",3L),"key","request-1");
  assertThat(result).isEqualTo(disabled);
  verify(mapper).updateStatus(1L,10L,"ACTIVE",3L);
  verify(audit).insert(1L,2L,"STATUS_CHANGE",10L,"request-1",LocalDateTime.of(2026,8,9,0,0));
 }
 @Test void merchantOperatorCannotEnableDisabledStore(){
  Store disabled=new Store(10L,1L,"S1","Name","P","acct","DISABLED",3L,LocalDateTime.now(),LocalDateTime.now());
  when(mapper.findByIdForUser(1L,2L,10L)).thenReturn(disabled);
  when(scope.canManageStoreStatus(1L,2L,10L)).thenReturn(false);
  assertThatThrownBy(()->configurableService.status(1L,2L,10L,new StoreStatusChangeRequest("ACTIVE",3L),"key",null))
   .isInstanceOf(StoreException.class).extracting(e->((StoreException)e).code()).isEqualTo("COMMON-1004");
  verify(mapper,never()).updateStatus(anyLong(),anyLong(),anyString(),anyLong());
  verifyNoInteractions(audit);
 }
 private static String hash(String value){try{return java.util.HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(value.getBytes(java.nio.charset.StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
