package com.shipflow.order.api;
import com.shipflow.common.api.ApiResponse; import com.shipflow.order.api.model.*; import com.shipflow.order.application.*; import jakarta.validation.Valid; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.security.oauth2.jwt.Jwt; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1/orders") public class ShipmentOrderManagementController {private final ShipmentOrderQueryApplicationService query;private final ShipmentOrderLifecycleApplicationService lifecycle;public ShipmentOrderManagementController(ShipmentOrderQueryApplicationService q,ShipmentOrderLifecycleApplicationService l){query=q;lifecycle=l;}
 @GetMapping public ApiResponse<ShipmentOrderPageResponse> list(@RequestParam(required=false)String status,@RequestParam(required=false)Long storeId,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int pageSize,@AuthenticationPrincipal Jwt jwt){return ApiResponse.success(query.list(tenant(jwt),status,storeId,page,pageSize));}
 @GetMapping("/{orderId}") public ApiResponse<ShipmentOrderResponse> get(@PathVariable Long orderId,@AuthenticationPrincipal Jwt jwt){return ApiResponse.success(query.get(tenant(jwt),orderId));}
 @PutMapping("/{orderId}") public ApiResponse<ShipmentOrderResponse> update(@PathVariable Long orderId,@Valid @RequestBody UpdateShipmentOrderRequest r,@RequestHeader(value="X-Request-Id",required=false)String requestId,@AuthenticationPrincipal Jwt jwt){return ApiResponse.success(lifecycle.updateDraft(tenant(jwt),user(jwt),orderId,r,requestId));}
 @PostMapping("/{orderId}/submit") public ApiResponse<ShipmentOrderResponse> submit(@PathVariable Long orderId,@Valid @RequestBody OrderActionRequest r,@RequestHeader(value="X-Request-Id",required=false)String requestId,@AuthenticationPrincipal Jwt jwt){return ApiResponse.success(lifecycle.submit(tenant(jwt),user(jwt),orderId,r,requestId));}
 @PostMapping("/{orderId}/cancel") public ApiResponse<ShipmentOrderResponse> cancel(@PathVariable Long orderId,@Valid @RequestBody OrderActionRequest r,@RequestHeader(value="X-Request-Id",required=false)String requestId,@AuthenticationPrincipal Jwt jwt){return ApiResponse.success(lifecycle.cancel(tenant(jwt),user(jwt),orderId,r,requestId));}
 private Long tenant(Jwt j){try{return Long.valueOf(j.getClaimAsString("tenant_id"));}catch(Exception e){throw new ShipmentOrderException("COMMON-1004",403);}} private Long user(Jwt j){try{return Long.valueOf(j.getSubject());}catch(Exception e){throw new ShipmentOrderException("COMMON-1004",403);}}}
