package com.shipflow.order.application;
import com.shipflow.order.api.model.*; import com.shipflow.order.domain.model.ShipmentOrder; import com.shipflow.order.domain.model.ShipmentOrderListQuery; import com.shipflow.order.mapper.ShipmentOrderListRow; import com.shipflow.order.mapper.ShipmentOrderMapper; import com.shipflow.store.mapper.StoreScopeMapper; import org.springframework.stereotype.Service; import java.time.ZoneOffset; import java.time.LocalDateTime; import java.util.Locale; import java.util.Set;
@Service public class ShipmentOrderQueryApplicationService { private final ShipmentOrderMapper mapper; private final StoreScopeMapper storeScopeMapper; public ShipmentOrderQueryApplicationService(ShipmentOrderMapper mapper,StoreScopeMapper storeScopeMapper){this.mapper=mapper;this.storeScopeMapper=storeScopeMapper;}
 public ShipmentOrderResponse get(Long tenant,Long id){return response(require(mapper.findById(tenant,id)));}
 public ShipmentOrderResponse getForCaller(Long tenant,Long user,Long id){ShipmentOrder order=require(mapper.findById(tenant,id));if(!storeScopeMapper.canAccessStore(tenant,user,order.storeId()))throw new ShipmentOrderException("COMMON-1006",404);return response(order);}
 public OrderDetailResponse getDetailForCaller(Long tenant,Long user,Long id){ShipmentOrderResponse order=getForCaller(tenant,user,id);var packages=mapper.findPackages(tenant,id).stream().map(p->new OrderDetailResponse.PackageView(p.id(),p.packageNo(),p.declaredWeight(),p.declaredLength(),p.declaredWidth(),p.declaredHeight(),p.volumeWeight(),p.chargeableWeight(),p.status(),mapper.findItems(tenant,p.id()))).toList();return new OrderDetailResponse(order,mapper.findAddresses(tenant,id),packages,mapper.findFeeAdjustments(tenant,id),mapper.findWarehouseRecords(tenant,id),mapper.findTrackingRecords(tenant,id),mapper.findExceptionSummaries(tenant,id),mapper.findTimeline(tenant,id));}
 public ShipmentOrderPageResponse list(Long tenant,String status,Long storeId,int page,int pageSize){if(page<1||pageSize<1||pageSize>100)throw new ShipmentOrderException("COMMON-1001",400); long total=mapper.count(tenant,status,storeId);return new ShipmentOrderPageResponse(page,pageSize,(total+pageSize-1)/pageSize,total,mapper.findPage(tenant,status,storeId,(page-1)*pageSize,pageSize).stream().map(this::response).toList());}
 public ShipmentOrderPageResponse listForCaller(Long tenant,Long user,String status,Long storeId,int page,int pageSize){return listForCaller(tenant,user,status,null,storeId,page,pageSize);}
 public ShipmentOrderPageResponse listForCaller(Long tenant,Long user,String status,String workbenchFilter,Long storeId,int page,int pageSize){if(page<1||pageSize<1||pageSize>100)throw new ShipmentOrderException("COMMON-1001",400);String filter=workbenchFilter==null||workbenchFilter.isBlank()?null:workbenchFilter.trim().toUpperCase(java.util.Locale.ROOT);if(filter!=null&&!java.util.Set.of("PENDING_FEE_CONFIRMATION","MISSING_ADDRESS").contains(filter))throw new ShipmentOrderException("COMMON-1001",400);long total=mapper.countForCaller(tenant,user,status,filter,storeId);return new ShipmentOrderPageResponse(page,pageSize,(total+pageSize-1)/pageSize,total,mapper.findPageForCaller(tenant,user,status,filter,storeId,(page-1)*pageSize,pageSize).stream().map(this::response).toList());}
 public ShipmentOrderPageResponse listFilteredForCaller(Long tenant, Long user, String orderNo, Long storeId, String status,
                                                         String destinationCountry, Long channelId, String trackingNo,
                                                         LocalDateTime createdFrom, LocalDateTime createdTo,
                                                         int page, int pageSize, String sortBy, String sortDirection) {
  if(page<1||pageSize<1||pageSize>100||!validRange(createdFrom,createdTo))throw new ShipmentOrderException("COMMON-1001",400);
  String normalizedStatus=optional(status, Set.of("DRAFT","PENDING_INBOUND","INBOUND","PENDING_PRICE_CONFIRMATION","READY_FOR_OUTBOUND","OUTBOUND","IN_TRANSIT","DELIVERED","CANCELLED","RETURNED","LOST"));
  String destination=optionalCountry(destinationCountry); String sort=optional(sortBy,Set.of("createdAt","orderNo","status","destinationCountry","channelId","estimatedFee"));
  String direction=optional(sortDirection,Set.of("ASC","DESC"));
  ShipmentOrderListQuery query=new ShipmentOrderListQuery(trim(orderNo,64),storeId,normalizedStatus,destination,channelId,trim(trackingNo,128),createdFrom,createdTo,page,pageSize,sort==null?"createdAt":sort,direction==null?"DESC":direction);
  long total=mapper.countFilteredForCaller(tenant,user,query);
  return new ShipmentOrderPageResponse(page,pageSize,(total+pageSize-1)/pageSize,total,mapper.findFilteredPageForCaller(tenant,user,query,(page-1)*pageSize).stream().map(this::response).toList());
 }
 private boolean validRange(LocalDateTime from,LocalDateTime to){return from==null||to==null||!from.isAfter(to);}
 private String optionalCountry(String value){String v=optional(value,null);if(v!=null&&!v.matches("[A-Z]{2}"))throw new ShipmentOrderException("COMMON-1001",400);return v;}
 private String optional(String value,Set<String> allowed){if(value==null||value.isBlank())return null;String v=value.trim().toUpperCase(Locale.ROOT);if(allowed!=null&&!allowed.contains(v)&&!allowed.contains(value.trim()))throw new ShipmentOrderException("COMMON-1001",400);return allowed!=null&&allowed.contains(value.trim())?value.trim():v;}
 private String trim(String value,int max){if(value==null||value.isBlank())return null;String result=value.trim();if(result.length()>max)throw new ShipmentOrderException("COMMON-1001",400);return result;}
 ShipmentOrder require(ShipmentOrder order){if(order==null)throw new ShipmentOrderException("COMMON-1006",404);return order;} ShipmentOrderResponse response(ShipmentOrder o){return new ShipmentOrderResponse(o.id(),o.orderNo(),o.storeId(),o.quoteId(),o.currentStatus(),o.destinationCountry(),o.channelId(),null,o.estimatedFee(),null,null,o.currency(),o.chargeableWeight(),o.version(),o.createdAt().atOffset(ZoneOffset.UTC));} ShipmentOrderResponse response(ShipmentOrderListRow o){return new ShipmentOrderResponse(o.id(),o.orderNo(),o.storeId(),o.quoteId(),o.status(),o.destinationCountry(),o.channelId(),o.trackingNo(),o.estimatedFee(),o.currentFee(),o.confirmedFee(),o.currency(),o.chargeableWeight(),o.version(),o.createdAt().atOffset(ZoneOffset.UTC));}}
