<script setup lang="ts">
import { reactive, ref } from 'vue'
import { useSubmit } from '@/composables/useSubmit'
import * as onboarding from '@/services/onboarding'
const form = reactive<onboarding.CreateOnboardingApplicationRequest>({ companyName: '', contactName: '', businessEmail: '', contactPhone: '', countryCode: '' })
const submitted = ref<onboarding.OnboardingApplication>()
const submit = useSubmit()
async function apply() { if (!form.companyName || !form.contactName || !form.businessEmail || !form.contactPhone || !/^[A-Za-z]{2}$/.test(form.countryCode)) { submit.errorMessage.value = '请完整填写企业与联系人信息，国家/地区使用两位代码。'; return } await submit.submit(async () => { submitted.value = await onboarding.submitOnboardingApplication({ ...form, countryCode: form.countryCode.toUpperCase() }) }) }
</script>
<template><section class="quote-page"><div class="container quote-page__header"><span class="kicker">商户入驻</span><h1>成为商户，获取正式报价</h1><p>提交企业信息后由平台审核；账号激活并登录、完成店铺与渠道配置后，即可创建正式报价并管理订单。访客预估不等于正式报价。</p></div><div class="container quote-shell"><div v-if="submitted" class="quote-success"><h2>入驻申请已提交</h2><p>申请编号：{{ submitted.applicationNo }}。审核结果将通过安全方式通知联系人。</p></div><form v-else class="quote-form" @submit.prevent="apply"><div class="quote-form__main form-grid"><label><span>企业名称</span><input v-model.trim="form.companyName" required /></label><label><span>联系人</span><input v-model.trim="form.contactName" required /></label><label><span>企业邮箱</span><input v-model.trim="form.businessEmail" type="email" required /></label><label><span>手机号 / WhatsApp</span><input v-model.trim="form.contactPhone" required /></label><label><span>所在国家 / 地区（两位代码）</span><input v-model.trim="form.countryCode" maxlength="2" placeholder="CN" required /></label><div class="form-actions form-grid__full"><span></span><button class="btn btn--primary" :disabled="submit.submitting.value">{{ submit.submitting.value ? '提交中…' : '提交入驻申请' }}</button></div><div v-if="submit.errorMessage.value" class="alert alert--error form-grid__full">{{ submit.errorMessage.value }}</div></div></form></div></section></template>
