<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ArrowLeft, RefreshCw } from '@lucide/vue'
import DataState from '@/components/DataState.vue'
import StatusBadge from '@/components/StatusBadge.vue'
import { getApiErrorMessage, toApiError } from '@/services/http'
import { getAvailableLogisticsChannel, type PublicLogisticsChannel } from '@/services/logistics'
import { displayValue } from '@/utils/display'

const route = useRoute(); const router = useRouter()
const detail = ref<PublicLogisticsChannel>(); const loading = ref(false); const error = ref(''); const errorCode = ref<string>(); const errorStatus = ref<number>(); const errorTraceId = ref<string>()
const channelId = computed(() => { const value = Number(route.params.channelId); return Number.isSafeInteger(value) && value > 0 ? value : undefined })
async function load() { if (!channelId.value) { error.value = '渠道编号无效。'; return } if (loading.value) return; loading.value = true; error.value = ''; errorCode.value = undefined; errorStatus.value = undefined; errorTraceId.value = undefined; try { detail.value = await getAvailableLogisticsChannel(String(channelId.value)) } catch (cause) { detail.value = undefined; const apiError = toApiError(cause); error.value = getApiErrorMessage(apiError, '渠道详情加载失败。'); errorCode.value = apiError.code; errorStatus.value = apiError.status; errorTraceId.value = apiError.traceId } finally { loading.value = false } }
function unavailable(field: string) { return detail.value?.unavailableFields.includes(field) ? '不可公开' : '尚未配置' }
function back() { void router.push({ name: 'app-logistics', query: route.query }) }
onMounted(() => void load()); watch(() => route.params.channelId, () => void load())
</script>
<template><section><div class="page-heading"><div><span class="kicker">物流基础资料</span><h1>渠道详情</h1><p>仅展示商家授权的公开渠道资料。</p></div><div class="page-actions"><button class="btn btn--secondary" type="button" @click="back"><ArrowLeft :size="16" />返回渠道目录</button><button class="btn btn--secondary" type="button" :disabled="loading || !channelId" @click="load"><RefreshCw :size="16" />{{ loading ? '刷新中…' : '刷新' }}</button></div></div><div class="panel table-panel"><DataState :loading="loading" :error="error" :error-code="errorCode" :status="errorStatus" :trace-id="errorTraceId" :retry="load" :empty="!detail && !error"><template v-if="detail"><div class="detail-grid"><div><span>物流商</span><strong>{{ detail.providerName }}</strong></div><div><span>渠道编码</span><strong>{{ detail.channelCode }}</strong></div><div><span>渠道名称</span><strong>{{ detail.channelName }}</strong></div><div><span>运输方式</span><strong>{{ displayValue('transportMode', detail.transportMode) }}</strong></div><div><span>服务国家</span><strong>{{ detail.serviceCountries.join('、') || '尚未配置' }}</strong></div><div><span>材积重除数</span><strong>{{ detail.volumeDivisor ?? unavailable('volumeDivisor') }}</strong></div><div><span>计费规则版本</span><strong>{{ detail.priceRuleVersion ?? unavailable('priceRuleVersion') }}</strong></div><div><span>生效时间</span><strong>{{ detail.effectiveFrom ? displayValue('updatedAt', detail.effectiveFrom) : unavailable('effectiveFrom') }}</strong></div><div><span>失效时间</span><strong>{{ detail.effectiveTo ? displayValue('updatedAt', detail.effectiveTo) : '未设置' }}</strong></div><div><span>支持货物属性</span><strong>{{ unavailable('supportedCargoAttributes') }}</strong></div><div><span>公开价格说明</span><strong>{{ unavailable('publicPriceDescription') }}</strong></div><div><span>当前状态</span><StatusBadge :status="detail.status" :label="displayValue('status', detail.status)" /></div></div><div v-if="detail.unavailableFields.length" class="alert alert--warning" role="status">不可公开字段：{{ detail.unavailableFields.join('、') }}</div></template></DataState></div></section></template>
